import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en' | 'kk';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ru: {
    // Top Bar
    headerStation: 'Станция Алматы-1',
    headerOperator: 'Менеджер: Айдана',
    search: 'Поиск',

    // Sidebar
    dashboard: 'Панель управления',
    pages: 'Страницы',
    newShipment: 'Новая отправка',
    activeShipments: 'Активные отправки',
    transit: 'Транзит',
    arrival: 'Прибытие',
    reports: 'Отчёты',
    wms: 'WMS склад',
    settings: 'Настройки',
    userProfile: 'Профиль пользователя',
    corporate: 'Корпоративные клиенты',

    // New Shipment
    newShipmentTitle: 'Новая отправка',
    newShipmentDesc: 'Оформление перевозки багажа',
    clientInfo: 'Информация о клиенте',
    cargoDetails: 'Детали груза',
    payment: 'Оплата',

    // Client Info
    clientType: 'Тип клиента',
    individual: 'Физическое лицо',
    legal: 'Юридическое лицо',
    clientName: 'ФИО / Название организации',
    enterClientName: 'Введите имя клиента',
    clientSource: 'Источник клиента',
    selectSource: 'Выберите источник',
    directContact: 'Прямое обращение',
    contractNumber: 'Номер договора',
    depositSystem: 'Депозитная система',
    route: 'Маршрут',
    from: 'Откуда',
    to: 'Куда',
    selectStation: 'Выберите станцию',
    departureDate: 'Дата отправления',
    transportCost: 'Стоимость перевозки',
    next: 'Далее',
    back: 'Назад',
    receiverName: 'ФИО Получателя',
    enterReceiverName: 'Введите имя получателя',
    receiverPhone: 'Телефон Получателя',
    recipientIsAnotherPerson: 'Получатель — другое лицо',

    // Cargo Details
    cargoDetailsTitle: 'Детали груза',
    mobiusTicket: 'Проверка билета Mobius',
    hasTicket: 'У клиента есть билет',
    ticketNumber: 'Номер билета',
    ticketDiscount: 'Применена скидка 50% по билету',
    weight: 'Вес (кг)',
    dimensions: 'Габариты (см)',
    dimensionsPlaceholder: 'Длина × Ширина × Высота',
    cargoValue: 'Ценность груза',
    fragile: 'Хрупкий',
    oversized: 'Негабаритный',
    packaging: 'Упаковка',
    selectPackaging: 'Выберите тип упаковки',
    woodCrate: 'Деревянная обрешётка',
    stretchFilm: 'Стрейч-пленка',
    cardboard: 'Картонная коробка',
    bag: 'Мешок',
    noPackaging: 'Без упаковки',
    declaredValue: 'Объявленная ценность (₸)',
    cargoDescription: 'Описание груза',
    describeContent: 'Опишите содержимое багажа',

    // Payment
    tariffCalculation: 'Расчёт тарифа',
    baseTransportCost: 'Базовая стоимость перевозки:',
    weightSurcharge: 'Доплата за вес:',
    fragileCargo: 'Хрупкий груз:',
    oversizedCargo: 'Негабаритный груз:',
    ticketDiscountLabel: 'Скидка по билету (50%):',
    totalPayment: 'Итого к оплате:',
    emailReceipt: 'Email для чека',
    cardInfo: 'Информация о карте',
    cardholderName: 'Имя держателя карты',
    countryRegion: 'Страна или регион',
    postalCode: 'Индекс',
    payButton: 'Оплатить',
    termsAgree: 'Нажимая "Оплатить", вы соглашаетесь с',
    termsOfUse: 'Условиями использования',
    privacyPolicy: 'Политикой конфиденциальности',
    and: 'и',

    // Active Shipments
    activeShipmentsTitle: 'Активные отправки',
    activeShipmentsDesc: 'Список отправок в обработке',
    searchPlaceholder: 'Поиск по номеру отправки, клиенту...',
    filters: 'Фильтры',
    number: 'Номер',
    client: 'Клиент',
    routeColumn: 'Маршрут',
    weightColumn: 'Вес',
    date: 'Дата',
    status: 'Статус',
    actions: 'Действия',
    details: 'Подробнее',
    inTransit: 'В пути',
    loaded: 'Погружен',
    arrived: 'Прибыл',

    // Transit
    transitTitle: 'Транзит',
    transitDesc: 'Регистрация перемещения багажа',
    qrScanning: 'Сканирование QR-кода',
    scanQrDesc: 'Отсканируйте QR-код на багаже для регистрации',
    startScanning: 'Начать сканирование',
    recentScans: 'Последние сканирования',
    loading: 'Погрузка',
    arrivalScan: 'Прибытие',
    issuance: 'Выдача',
    action: 'Действие',

    // Arrival
    arrivalTitle: 'Прибытие',
    arrivalDesc: 'Управление прибывшим багажом',
    arrivedShipments: 'Прибывшие отправки',
    notifyAll: 'Уведомить всех',
    notified: 'Уведомлен',
    arrivedFrom: 'Откуда:',
    arrivedAt: 'Прибыл:',
    phone: 'Телефон:',
    notify: 'Уведомить',
    issue: 'Выдать',

    // Reports
    reportsTitle: 'Отчёты',
    reportsDesc: 'Формирование и просмотр отчетов',
    fo3Report: 'Отчёт FO-3',
    financialReport: 'Финансовый отчёт',
    shipmentsReport: 'Отчёт по отправкам',
    generalStats: 'Общая статистика',
    auditLog: 'Журнал аудита',
    userActions: 'Действия пользователей',
    routeReport: 'Отчёт по маршрутам',
    routeAnalysis: 'Анализ направлений',
    allUsers: 'Все пользователи',
    allRoutes: 'Все маршруты',
    generate: 'Сформировать',
    export: 'Выгрузить',

    // WMS
    wmsTitle: 'WMS склад',
    wmsDesc: 'Автоматизированная система складских ячеек',
    storageCells: 'Складские ячейки',
    cellStatus: 'Статус ячеек',
    free: 'Свободно',
    occupied: 'Занято',
    maintenance: 'Обслуживание',
    selfService: 'Самообслуживание',
    selfServiceDesc: 'Сдача багажа без участия оператора',
    scanDocument: 'Сканировать документ',
    scanDocumentDesc: 'Отсканируйте паспорт или QR-код для начала',
    placeInCell: 'Поместите багаж в ячейку',
    placeInCellDesc: 'Откройте ячейку и поместите багаж внутрь',
    autoMeasure: 'Автоматическое измерение',
    autoMeasureDesc: 'Вес и габариты будут измерены автоматически',
    confirmShipment: 'Подтвердите отправку',
    confirmShipmentDesc: 'Проверьте данные и получите QR-код',
    cellNumber: 'Ячейка',
    openCell: 'Открыть ячейку',
    closeCell: 'Закрыть ячейку',

    // Settings
    settingsTitle: 'Настройки',
    settingsDesc: 'Настройки системы и профиля',
    languageSettings: 'Язык интерфейса',
    themeSettings: 'Тема оформления',
    light: 'Светлая',
    dark: 'Тёмная',
    notificationSettings: 'Уведомления',
    emailNotifications: 'Email уведомления',
    smsNotifications: 'SMS уведомления',
    saveSettings: 'Сохранить настройки',

    // Common
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    close: 'Закрыть',
    save: 'Сохранить',
    delete: 'Удалить',
    edit: 'Редактировать',

    // Shipment created
    shipmentCreated: 'Отправка создана',
    documentsReady: 'Документы сформированы и готовы к печати',
    printDocuments: 'Печать документов',
    newShipmentButton: 'Новая отправка',

    // Manager Dashboard
    managerDashboard: 'Панель руководителя',
    managerDashboardDesc: 'Аналитика и статистика работы системы',
    monthlyShipments: 'Запланировано перевозок',
    completedShipments: 'Выполнено перевозок',
    activeContracts: 'Активных договоров',
    wagonsInWork: 'Вагонов в работе',
    month: 'Месяц',
    active: 'Активные',
    total: 'Всего',
    vsLastMonth: 'к прошлому месяцу',
    planCompletion: 'выполнения плана',
    newPerWeek: 'новых за неделю',
    withCargo: 'под грузом',
    routeAnalysisTitle: 'Анализ маршрутов',
    topRoutes: 'Топ маршрутов',
    shipments: 'отправок',
    wagonStatusTitle: 'Статус вагонов',
    underCargo: 'Под грузом',
    atStation: 'На станции',
    inIdle: 'В простое',
    empty: 'Порожний',
    inRepair: 'В ремонте',
    financialMetrics: 'Финансовые показатели',
    revenue: 'Выручка',
    expenses: 'Расходы',
    profit: 'Прибыль',
    currentMonth: 'Текущий месяц',
    thisMonth: 'В этом месяце',
    thisQuarter: 'В этом квартале',
    revenueByRoute: 'Выручка по направлениям',
    totalRevenue: 'Общая выручка',
    wagonsByStatus: 'Вагоны по статусу',
    wagons: 'вагонов',

    plannedActual: 'Плановые и фактические показатели',
    positiveTrend: 'Положительная динамика',
    halfYearPlan: 'План на полугодие',
    actualRevenue: 'Фактическая выручка',
    planExecution: 'Выполнение плана',
    planned: 'Запланировано',
    actual: 'Фактически',

    // Admin Dashboard
    adminDashboard: 'Панель администратора',
    employeeManagement: 'Управление сотрудниками',
    employeeManagementDesc: 'Создание и управление учётными записями',
    totalEmployees: 'Всего сотрудников',
    activeEmployees: 'Активных',
    operators: 'Менеджеры',
    receivers: 'Приёмщики',
    createEmployee: 'Создать сотрудника',
    name: 'Имя',
    email: 'Email',
    role: 'Роль',
    station: 'Станция',
    createdAt: 'Создан',
    statusEmployee: 'Статус',
    actionsEmployee: 'Действия',
    createNewEmployee: 'Создание нового сотрудника',
    fullName: 'Полное имя',
    enterFullName: 'Введите полное имя',
    enterEmail: 'Введите email',
    password: 'Пароль',
    enterPassword: 'Введите пароль',
    operator: 'Менеджер',
    receiver: 'Приёмщик',
    roleAdmin: 'Администратор',
    roleManager: 'Руководитель',
    roleAuditor: 'Ревизор',
    roleMobileGroup: 'Мобильная группа',

    createButton: 'Создать',
    searchByNameEmail: 'Поиск по имени, email или станции...',
    newEmployee: 'Новый сотрудник',
    employeeCreatedSuccess: 'Сотрудник успешно создан!',
    deleteEmployeeConfirm: 'Вы уверены, что хотите удалить этого сотрудника?',
    employeeLabel: 'Сотрудник',
    dateCreated: 'Дата создания',
    activeStatus: 'Активен',
    inactiveStatus: 'Неактивен',
    noEmployeesFound: 'Сотрудники не найдеы',

    // Corporate Dashboard
    corporateDashboard: 'Корпоративная панель',
    corporateClientsDesc: 'Управление юридическими лицами',
    addClient: 'Добавить клиента',
    searchByNameOrContract: 'Поиск по названию, договору...',
    noCorporateClients: 'Нет корпоративных клиентов.',
    withoutName: 'Без названия',
    activeCount: 'активных',
    binContract: 'БИН/Договор:',
    contactPerson: 'Контактное лицо:',
    depositSumMsg: 'Сумма пополнения (₸):',
    addCorporateClient: 'Добавить корпоративного клиента',
    companyName: 'Название компании',
    bin: 'БИН',
    fullName: 'ФИО',
    passwordLabel: 'Пароль',
    depositAmount: 'Сумма пополнения депозита (₸)',
    cancel: 'Отмена',
    createClient: 'Создать клиента',
    creating: 'Создание...',
    topUpDeposit: 'Пополнить депозит',
    topUpAmount: 'Сумма пополнения (₸)',
    paymentMethod: 'Способ оплаты',
    bankCard: 'Банковская карта (Kaspi, Halyk)',
    pay: 'Оплатить',
    processing: 'Обработка...',
    topUp: 'Пополнить',
    myShipments: 'Мои отправки',
    myShipmentsDesc: 'Управление корпоративными перевозками',

    pendingPickup: 'Ожидают забора',
    totalThisMonth: 'Всего за месяц',
    avgDeliveryTime: 'Среднее время доставки',
    days: 'дней',
    createNewShipment: 'Создать отправку',
    recentShipments: 'Недавние отправки',
    viewAll: 'Посмотреть все',
    deposit: 'Депозит',
    thisMonthLabel: 'За месяц',
    documents: 'Документы',
    generateDocuments: 'Сформировать документы',
    invoice: 'Счёт-фактура',
    actOfWork: 'Акт выполненных работ',

    waybillRegistry: 'Реестр накладных',

    // Individual Dashboard
    individualDashboard: 'Личный кабинет',
    myBaggage: 'Мой багаж',
    myBaggageDesc: 'Отслеживание отправок',
    trackShipment: 'Отследить отправку',
    trackingNumber: 'Номер отправки',
    enterTrackingNumber: 'Введите номер отправки',
    track: 'Отследить',
    noShipmentsYet: 'У вас пока нет отправок',
    createFirstShipment: 'Создайте свою первую отправку',

    // Receiver Dashboard
    receiverDashboard: 'Панель приёмщика',
    baggageIssuance: 'Выдача багажа',
    baggageIssuanceDesc: 'Управление выдачей багажа',
    readyForPickup: 'Готово к выдаче',
    issuedToday: 'Выдано сегодня',
    notifiedClients: 'Уведомлено клиентов',
    avgWaitTime: 'Среднее время ожидания',
    minutes: 'минут',
    scanOrEnter: 'Сканировать или ввести номер',
    scanQrOrEnter: 'Отсканируйте QR-код или введите номер отправки',
    shipmentNumber: 'Номер отправки',
    enterShipmentNumber: 'Введите номер отправки',
    findShipment: 'Найти отправку',
    readyForIssue: 'Готово к выдач��',
    issueToClient: 'Выдать клиенту',
  },

  en: {
    // Top Bar
    headerStation: 'Almaty-1 Station',
    headerOperator: 'Manager: Aidana',
    search: 'Search',

    // Sidebar
    dashboard: 'Dashboard',
    pages: 'Pages',
    newShipment: 'New Shipment',
    activeShipments: 'Active Shipments',
    transit: 'Transit',
    arrival: 'Arrival',
    reports: 'Reports',
    wms: 'WMS Warehouse',
    settings: 'Settings',
    userProfile: 'User Profile',
    corporate: 'Corporate Clients',

    // New Shipment
    newShipmentTitle: 'New Shipment',
    newShipmentDesc: 'Baggage transportation registration',
    clientInfo: 'Client Information',
    cargoDetails: 'Cargo Details',
    payment: 'Payment',

    // Client Info
    clientType: 'Client Type',
    individual: 'Individual',
    legal: 'Legal Entity',
    clientName: 'Full Name / Organization Name',
    enterClientName: 'Enter client name',
    clientSource: 'Client Source',
    selectSource: 'Select source',
    directContact: 'Direct Contact',
    contractNumber: 'Contract Number',
    depositSystem: 'Deposit System',
    route: 'Route',
    from: 'From',
    to: 'To',
    selectStation: 'Select station',
    departureDate: 'Departure Date',
    transportCost: 'Transport Cost',
    next: 'Next',
    back: 'Back',
    receiverName: 'Receiver Name',
    enterReceiverName: 'Enter receiver name',
    receiverPhone: 'Receiver Phone',
    recipientIsAnotherPerson: 'Recipient is another person',

    // Cargo Details
    cargoDetailsTitle: 'Cargo Details',
    mobiusTicket: 'Mobius Ticket Check',
    hasTicket: 'Customer has a ticket',
    ticketNumber: 'Ticket Number',
    ticketDiscount: '50% discount applied with ticket',
    weight: 'Weight (kg)',
    dimensions: 'Dimensions (cm)',
    dimensionsPlaceholder: 'Length × Width × Height',
    cargoValue: 'Cargo Value',
    fragile: 'Fragile',
    oversized: 'Oversized',
    packaging: 'Packaging',
    selectPackaging: 'Select packaging type',
    woodCrate: 'Wooden Crate',
    stretchFilm: 'Stretch Film',
    cardboard: 'Cardboard Box',
    bag: 'Bag',
    noPackaging: 'No Packaging',
    declaredValue: 'Declared Value (₸)',
    cargoDescription: 'Cargo Description',
    describeContent: 'Describe baggage contents',

    // Payment
    tariffCalculation: 'Tariff Calculation',
    baseTransportCost: 'Base transport cost:',
    weightSurcharge: 'Weight surcharge:',
    fragileCargo: 'Fragile cargo:',
    oversizedCargo: 'Oversized cargo:',
    ticketDiscountLabel: 'Ticket discount (50%):',
    totalPayment: 'Total payment:',
    emailReceipt: 'Email for receipt',
    cardInfo: 'Card Information',
    cardholderName: 'Cardholder Name',
    countryRegion: 'Country or Region',
    postalCode: 'Postal Code',
    payButton: 'Pay',
    termsAgree: 'By clicking "Pay", you agree to',
    termsOfUse: 'Terms of Use',
    privacyPolicy: 'Privacy Policy',
    and: 'and',

    // Active Shipments
    activeShipmentsTitle: 'Active Shipments',
    activeShipmentsDesc: 'List of shipments in progress',
    searchPlaceholder: 'Search by shipment number, client...',
    filters: 'Filters',
    number: 'Number',
    client: 'Client',
    routeColumn: 'Route',
    weightColumn: 'Weight',
    date: 'Date',
    status: 'Status',
    actions: 'Actions',
    details: 'Details',
    inTransit: 'In Transit',
    loaded: 'Loaded',
    arrived: 'Arrived',

    // Transit
    transitTitle: 'Transit',
    transitDesc: 'Baggage movement registration',
    qrScanning: 'QR Code Scanning',
    scanQrDesc: 'Scan the QR code on baggage for registration',
    startScanning: 'Start Scanning',
    recentScans: 'Recent Scans',
    loading: 'Loading',
    arrivalScan: 'Arrival',
    issuance: 'Issuance',
    action: 'Action',

    // Arrival
    arrivalTitle: 'Arrival',
    arrivalDesc: 'Arrived baggage management',
    arrivedShipments: 'Arrived Shipments',
    notifyAll: 'Notify All',
    notified: 'Notified',
    arrivedFrom: 'From:',
    arrivedAt: 'Arrived:',
    phone: 'Phone:',
    notify: 'Notify',
    issue: 'Issue',

    // Reports
    reportsTitle: 'Reports',
    reportsDesc: 'Report generation and viewing',
    fo3Report: 'FO-3 Report',
    financialReport: 'Financial Report',
    shipmentsReport: 'Shipments Report',
    generalStats: 'General Statistics',
    auditLog: 'Audit Log',
    userActions: 'User Actions',
    routeReport: 'Route Report',
    routeAnalysis: 'Route Analysis',
    allUsers: 'All Users',
    allRoutes: 'All Routes',
    generate: 'Generate',
    export: 'Export',

    // WMS
    wmsTitle: 'WMS Warehouse',
    wmsDesc: 'Automated storage cell system',
    storageCells: 'Storage Cells',
    cellStatus: 'Cell Status',
    free: 'Free',
    occupied: 'Occupied',
    maintenance: 'Maintenance',
    selfService: 'Self-Service',
    selfServiceDesc: 'Baggage drop-off without operator',
    scanDocument: 'Scan Document',
    scanDocumentDesc: 'Scan passport or QR code to start',
    placeInCell: 'Place in Cell',
    placeInCellDesc: 'Open cell and place baggage inside',
    autoMeasure: 'Auto Measurement',
    autoMeasureDesc: 'Weight and dimensions will be measured automatically',
    confirmShipment: 'Confirm Shipment',
    confirmShipmentDesc: 'Check data and receive QR code',
    cellNumber: 'Cell',
    openCell: 'Open Cell',
    closeCell: 'Close Cell',

    // Settings
    settingsTitle: 'Settings',
    settingsDesc: 'System and profile settings',
    languageSettings: 'Interface Language',
    themeSettings: 'Theme',
    light: 'Light',
    dark: 'Dark',
    notificationSettings: 'Notifications',
    emailNotifications: 'Email Notifications',
    smsNotifications: 'SMS Notifications',
    saveSettings: 'Save Settings',

    // Common
    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',

    // Shipment created
    shipmentCreated: 'Shipment Created',
    documentsReady: 'Documents generated and ready to print',
    printDocuments: 'Print Documents',
    newShipmentButton: 'New Shipment',

    // Manager Dashboard
    managerDashboard: 'Manager Dashboard',
    managerDashboardDesc: 'Analytics and system performance statistics',
    monthlyShipments: 'Planned shipments',
    completedShipments: 'Completed shipments',
    activeContracts: 'Active contracts',
    wagonsInWork: 'Wagons in work',
    month: 'Month',
    active: 'Active',
    total: 'Total',
    vsLastMonth: 'vs last month',
    planCompletion: 'plan completion',
    newPerWeek: 'new per week',
    withCargo: 'with cargo',
    routeAnalysisTitle: 'Route analysis',
    topRoutes: 'Top routes',
    shipments: 'shipments',
    wagonStatusTitle: 'Wagon status',
    underCargo: 'Under cargo',
    atStation: 'At station',
    inIdle: 'Idle',
    empty: 'Empty',
    inRepair: 'In repair',
    financialMetrics: 'Financial metrics',
    revenue: 'Revenue',
    expenses: 'Expenses',
    profit: 'Profit',
    currentMonth: 'Current month',
    thisMonth: 'This month',
    thisQuarter: 'This quarter',
    revenueByRoute: 'Revenue by route',
    totalRevenue: 'Total revenue',
    wagonsByStatus: 'Wagons by status',
    wagons: 'wagons',

    plannedActual: 'Planned and actual metrics',
    positiveTrend: 'Positive trend',
    halfYearPlan: 'Half-year plan',
    actualRevenue: 'Actual revenue',
    planExecution: 'Plan execution',
    planned: 'Planned',
    actual: 'Actual',

    // Admin Dashboard
    adminDashboard: 'Admin Dashboard',
    employeeManagement: 'Employee Management',
    employeeManagementDesc: 'Create and manage user accounts',
    totalEmployees: 'Total employees',
    activeEmployees: 'Active',
    operators: 'Managers',
    receivers: 'Receivers',
    createEmployee: 'Create employee',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    station: 'Station',
    createdAt: 'Created at',
    statusEmployee: 'Status',
    actionsEmployee: 'Actions',
    createNewEmployee: 'Create new employee',
    fullName: 'Full name',
    enterFullName: 'Enter full name',
    enterEmail: 'Enter email',
    password: 'Password',
    enterPassword: 'Enter password',
    operator: 'Manager',
    receiver: 'Receiver',
    roleAdmin: 'Administrator',
    roleManager: 'Manager',
    roleAuditor: 'Auditor',
    roleMobileGroup: 'Mobile Group',

    createButton: 'Create',
    searchByNameEmail: 'Search by name, email or station...',
    newEmployee: 'New employee',
    employeeCreatedSuccess: 'Employee successfully created!',
    deleteEmployeeConfirm: 'Are you sure you want to delete this employee?',
    employeeLabel: 'Employee',
    dateCreated: 'Date created',
    activeStatus: 'Active',
    inactiveStatus: 'Inactive',
    noEmployeesFound: 'No employees found',

    // Corporate Dashboard
    corporateDashboard: 'Corporate Dashboard',
    corporateClientsDesc: 'Manage legal entities',
    addClient: 'Add Client',
    searchByNameOrContract: 'Search by name, contract...',
    noCorporateClients: 'No corporate clients.',
    withoutName: 'Unnamed',
    activeCount: 'active',
    binContract: 'BIN/Contract:',
    contactPerson: 'Contact Person:',
    depositSumMsg: 'Deposit Amount (₸):',
    addCorporateClient: 'Add Corporate Client',
    companyName: 'Company Name',
    bin: 'BIN',
    fullName: 'Full Name',
    passwordLabel: 'Password',
    depositAmount: 'Deposit Top-up Amount (₸)',
    cancel: 'Cancel',
    createClient: 'Create Client',
    creating: 'Creating...',
    topUpDeposit: 'Top Up Deposit',
    topUpAmount: 'Top-up Amount (₸)',
    paymentMethod: 'Payment Method',
    bankCard: 'Bank Card (Kaspi, Halyk)',
    pay: 'Pay',
    processing: 'Processing...',
    topUp: 'Top Up',
    myShipments: 'My Shipments',
    myShipmentsDesc: 'Manage corporate shipments',

    pendingPickup: 'Pending pickup',
    totalThisMonth: 'Total this month',
    avgDeliveryTime: 'Average delivery time',
    days: 'days',
    createNewShipment: 'Create new shipment',
    recentShipments: 'Recent shipments',
    viewAll: 'View all',
    deposit: 'Deposit',
    thisMonthLabel: 'For the month',
    documents: 'Documents',
    generateDocuments: 'Generate documents',
    invoice: 'Invoice',
    actOfWork: 'Act of work performed',

    waybillRegistry: 'Waybill registry',

    // Individual Dashboard
    individualDashboard: 'Individual Dashboard',
    myBaggage: 'My Baggage',
    myBaggageDesc: 'Track shipments',
    trackShipment: 'Track shipment',
    trackingNumber: 'Tracking number',
    enterTrackingNumber: 'Enter tracking number',
    track: 'Track',
    noShipmentsYet: 'You have no shipments yet',
    createFirstShipment: 'Create your first shipment',

    // Receiver Dashboard
    receiverDashboard: 'Receiver Dashboard',
    baggageIssuance: 'Baggage Issuance',
    baggageIssuanceDesc: 'Manage baggage issuance',
    readyForPickup: 'Ready for pickup',
    issuedToday: 'Issued today',
    notifiedClients: 'Notified clients',
    avgWaitTime: 'Average wait time',
    minutes: 'minutes',
    scanOrEnter: 'Scan or enter number',
    scanQrOrEnter: 'Scan QR code or enter shipment number',
    shipmentNumber: 'Shipment number',
    enterShipmentNumber: 'Enter shipment number',
    findShipment: 'Find shipment',
    readyForIssue: 'Ready for issue',
    issueToClient: 'Issue to client',
  },

  kk: {
    // Top Bar
    headerStation: 'Алматы-1 станциясы',
    headerOperator: 'Менеджер: Айдана',
    search: 'Іздеу',

    // Sidebar
    dashboard: 'Басқару панелі',
    pages: 'Беттер',
    newShipment: 'Жаңа жөнелту',

    transit: 'Транзит',
    arrival: 'Келу',
    reports: 'Есептер',
    wms: 'WMS қойма',
    settings: 'Баптаулар',
    userProfile: 'Пайдаланушы профилі',
    corporate: 'Корпоративті клиенттер',

    // New Shipment
    newShipmentTitle: 'Жаңа жөнелту',
    newShipmentDesc: 'Багажды тасымалдауды ресімдеу',
    clientInfo: 'Клиент туралы мәлімет',
    cargoDetails: 'Жүк туралы мәліметтер',
    payment: 'Төлем',

    // Client Info
    clientType: 'Клиент түрі',
    individual: 'Жеке тұлға',
    legal: 'Заңды тұлға',
    clientName: 'Аты-жөні / Ұйым атауы',
    enterClientName: 'Клиент атын енгізіңіз',
    clientSource: 'Клиент көзі',
    selectSource: 'Көзді таңдаңыз',
    directContact: 'Тікелей өтініш',
    contractNumber: 'Шарт нөмірі',
    depositSystem: 'Депозиттік жүйе',
    route: 'Бағыт',
    from: 'Қайдан',
    to: 'Қайда',
    selectStation: 'Станцияны таңдаңыз',
    departureDate: 'Жөнелту күні',
    transportCost: 'Тасымалдау құны',
    next: 'Әрі қарай',
    back: 'Артқа',
    receiverName: 'Алушының аты-жөні',
    enterReceiverName: 'Алушының атын енгізіңіз',
    receiverPhone: 'Алушының телефоны',
    recipientIsAnotherPerson: 'Алушы - басқа тұлға',

    // Cargo Details
    cargoDetailsTitle: 'Жүк туралы мәліметтер',
    mobiusTicket: 'Mobius билетін тексеру',
    hasTicket: 'Клиентте билет бар',
    ticketNumber: 'Билет нөмірі',
    ticketDiscount: 'Билет бойынша 50% жеңілдік қолданылды',
    weight: 'Салмақ (кг)',
    dimensions: 'Өлшемдер (см)',
    dimensionsPlaceholder: 'Ұзындығы × Ені × Биіктігі',
    cargoValue: 'Жүк құндылығы',
    fragile: 'Сынғыш',
    oversized: 'Габаритсіз',
    packaging: 'Қаптама',
    selectPackaging: 'Қаптама түрін таңдаңыз',
    woodCrate: 'Ағаш қаптама',
    stretchFilm: 'Стретч-пленка',
    cardboard: 'Картон қорап',
    bag: 'Қап',
    noPackaging: 'Қаптамасыз',
    declaredValue: 'Жариялаған құны (₸)',
    cargoDescription: 'Жүктің сипаттамасы',
    describeContent: 'Багаж мазмұнын сипаттаңыз',

    // Payment
    tariffCalculation: 'Тариф есебі',
    baseTransportCost: 'Тасымалдаудың базалық құны:',
    weightSurcharge: 'Салмақ үшін қосымша төлем:',
    fragileCargo: 'Сынғыш жүк:',
    oversizedCargo: 'Габаритсіз жүк:',
    ticketDiscountLabel: 'Билет бойынша жеңілдік (50%):',
    totalPayment: 'Барлығы төлеу керек:',
    emailReceipt: 'Чек үшін Email',
    cardInfo: 'Карта туралы мәлімет',
    cardholderName: 'Карта иесінің аты',
    countryRegion: 'Ел немесе аймақ',
    postalCode: 'Индекс',
    payButton: 'Төлеу',
    termsAgree: '"Төлеу" түймесін басу арқылы сіз келісесіз',
    termsOfUse: 'Пайдалану шарттарымен',
    privacyPolicy: 'Құпиялылық саясатымен',
    and: 'және',

    // Active Shipments
    activeShipmentsTitle: 'Белсенді жөнелтулер',
    activeShipmentsDesc: 'Өңдеудегі жөнелтулер тізімі',
    searchPlaceholder: 'Жөнелту нөмірі, клиент бойынша іздеу...',
    filters: 'Сүзгілер',
    number: 'Нөмір',
    client: 'Клиент',
    routeColumn: 'Бағыт',
    weightColumn: 'Салмақ',
    date: 'Күн',
    status: 'Күй',
    actions: 'Әрекеттер',
    details: 'Толығырақ',
    inTransit: 'Жолда',
    loaded: 'Тиелген',
    arrived: 'Келді',

    // Transit
    transitTitle: 'Транзит',
    transitDesc: 'Багаж қозғалысын тіркеу',
    qrScanning: 'QR-кодты ска��ерлеу',
    scanQrDesc: 'Тіркеу үшін багаждағы QR-кодты сканерлеңіз',
    startScanning: 'Сканерлеуді бастау',
    recentScans: 'Соңғы сканерлеулер',
    loading: 'Тиеу',
    arrivalScan: 'Келу',
    issuance: 'Беру',
    action: 'Әрекет',

    // Arrival
    arrivalTitle: 'Келу',
    arrivalDesc: 'Келген багажды басқару',
    arrivedShipments: 'Келген жөнелтулер',
    notifyAll: 'Барлығын хабарландыру',
    notified: 'Хабарландырылды',
    arrivedFrom: 'Қайдан:',
    arrivedAt: 'Келді:',
    phone: 'Телефон:',
    notify: 'Хабарландыру',
    issue: 'Беру',

    // Reports
    reportsTitle: 'Есептер',
    reportsDesc: 'Есептерді қалыптастыру және қарау',
    fo3Report: 'FO-3 есебі',
    financialReport: 'Қаржылық есеп',
    shipmentsReport: 'Жөнелтулер бойынша есеп',
    generalStats: 'Жалпы статистика',
    auditLog: 'Аудит журналы',
    userActions: 'Пайдаланушы әрекеттері',
    routeReport: 'Бағыттар бойынша есеп',
    routeAnalysis: 'Бағыттарды талдау',
    allUsers: 'Барлық пайдаланушылар',
    allRoutes: 'Барлық бағыттар',
    generate: 'Қалыптастыру',
    export: 'Жүктеп алу',

    // WMS
    wmsTitle: 'WMS қойма',
    wmsDesc: 'Автоматтандырылған қойма ұяшықтары жүйесі',
    storageCells: 'Қойма ұяшықтары',
    cellStatus: 'Ұяшықтар күйі',
    free: 'Бос',
    occupied: 'Толық',
    maintenance: 'Қызмет көрсету',
    selfService: 'Өзін-өзі қызмет көрсету',
    selfServiceDesc: 'Менеджерсіз багаж тапсыру',
    scanDocument: 'Құжатты сканерлеу',
    scanDocumentDesc: 'Бастау үшін төлқұжатты немесе QR-кодты сканерлеңіз',
    placeInCell: 'Ұяшыққа салыңыз',
    placeInCellDesc: 'Ұяшықты ашып, багажды ішіне салыңыз',
    autoMeasure: 'Автоматты өлшеу',
    autoMeasureDesc: 'Салмақ пен өлшемдер автоматты түрде өлшенеді',
    confirmShipment: 'Жөнелтуді растаңыз',
    confirmShipmentDesc: 'Деректерді тексеріп, QR-кодты алыңыз',
    cellNumber: 'Ұяшық',
    openCell: 'Ұяшықты ашу',
    closeCell: 'Ұяшықты жабу',

    // Settings
    settingsTitle: 'Баптаулар',
    settingsDesc: 'Жүйе және профиль баптаулары',
    languageSettings: 'Интерфейс тілі',
    themeSettings: 'Тақырып',
    light: 'Ашық',
    dark: 'Қараңғы',
    notificationSettings: 'Хабарландырулар',
    emailNotifications: 'Email хабарландырулары',
    smsNotifications: 'SMS хабарландырулары',
    saveSettings: 'Баптауларды сақтау',

    // Common
    cancel: 'Болдырмау',
    confirm: 'Растау',
    close: 'Жабу',
    save: 'Сақтау',
    delete: 'Жою',
    edit: 'Өңдеу',

    // Shipment created
    shipmentCreated: 'Жөнелту жасалды',
    documentsReady: 'Құжаттар қалыптастырылды және басып шығаруға дайын',
    printDocuments: 'Құжаттарды басып шығару',
    newShipmentButton: 'Жаңа жөнелту',

    // Manager Dashboard
    managerDashboard: 'Басқару панелі',
    managerDashboardDesc: 'Аналитика және жүйенің іштету статистикасы',
    monthlyShipments: 'Айлық жөнелтулер',
    completedShipments: 'Жүргізілген жөнелтулер',
    activeContracts: 'Активті шарттар',
    wagonsInWork: 'Жұмысдағы вагондар',
    month: 'Ай',
    active: 'Активті',
    total: 'Жалпы',
    vsLastMonth: 'өтінген айға қарау',
    planCompletion: 'планды орындалдыру',
    newPerWeek: 'жетідеңде жаңа',
    withCargo: 'жүктің астында',
    routeAnalysisTitle: 'Бағыттарды талдау',
    topRoutes: 'Жоғары бағыттар',
    shipments: 'жөнелтулер',
    wagonStatusTitle: 'Вагондардың күйі',
    underCargo: 'Жүктің астында',
    atStation: 'Станцияда',
    inIdle: 'Тұрғыз',
    empty: 'Бос',
    inRepair: 'Түзету үшін',
    financialMetrics: 'Финансалық мәліметтер',
    revenue: 'Келісім',
    expenses: 'Шығу',
    profit: 'Жылдамдық',
    currentMonth: 'Ағымдағы ай',
    thisMonthLabel: 'Бұл ай',
    thisQuarter: 'Бұл қыртышақ',
    revenueByRoute: 'Бағыттар бойынша келісім',
    totalRevenue: 'Жалпы келісім',
    wagonsByStatus: 'Вагондардың күйі бойынша',
    wagons: 'вагондар',

    plannedActual: 'Пландағы және фактическі мәліметтер',
    positiveTrend: 'Позитивті тенденция',
    halfYearPlan: 'Жарым жылдық план',
    actualRevenue: 'Фактическі келісім',
    planExecution: 'Планды орындалдыру',
    planned: 'Пландағы',
    actual: 'Фактическі',

    // Admin Dashboard
    adminDashboard: 'Басқару панелі',
    employeeManagement: 'Қызметкерлерді басқару',
    employeeManagementDesc: 'Қызметкерлерді тіркеу және басқару',
    totalEmployees: 'Барлық қызметкерлер',
    activeEmployees: 'Активті',
    operators: 'Менеджерлер',
    receivers: 'Қабылдаушылар',
    createEmployee: 'Қызметкер тіркемесін жасау',
    name: 'Аты',
    email: 'Email',
    role: 'Рөл',
    station: 'Станция',
    createdAt: 'Тіркелген күні',
    statusEmployee: 'Күйі',
    actionsEmployee: 'Әрекеттер',
    createNewEmployee: 'Жаңа қызметкер тіркемесін жасау',
    fullName: 'Толық аты',
    enterFullName: 'Толық атын енгізіңіз',
    enterEmail: 'Email-ді енгізіңіз',
    password: 'Құпия сөз',
    enterPassword: 'Құпия сөзді енгізіңіз',
    operator: 'Менеджер',
    receiver: 'Қабылдаушы',
    roleAdmin: 'Әкімші',
    roleManager: 'Басшы',
    roleAuditor: 'Ревизор',
    roleMobileGroup: 'Мобильді топ',

    createButton: 'Жасау',
    searchByNameEmail: 'Аты, email немесе станция бойынша іздеу...',
    newEmployee: 'Жаңа қызметкер',
    employeeCreatedSuccess: 'Қызметкер сәтті тіркелген!',
    deleteEmployeeConfirm: 'Бұл қызметкерді өшіру керек пішіндеңіз бе?',
    employeeLabel: 'Қызметкер',
    dateCreated: 'Тіркелген күні',
    activeStatus: 'Активті',
    inactiveStatus: 'Пассивті',
    noEmployeesFound: 'Қызметкерлер табылған жок',

    // Corporate Dashboard
    corporateDashboard: 'Корпоративті панель',
    corporateClientsDesc: 'Заңды тұлғаларды басқару',
    addClient: 'Клиент қосу',
    searchByNameOrContract: 'Аты немесе шарт бойынша іздеу...',
    noCorporateClients: 'Корпоративті клиенттер жоқ.',
    withoutName: 'Атаусыз',
    activeCount: 'белсенді',
    binContract: 'БСН/Шарт:',
    contactPerson: 'Байланыс тұлғасы:',
    depositSumMsg: 'Толықтыру сомасы (₸):',
    addCorporateClient: 'Корпоративті клиент қосу',
    companyName: 'Компания атауы',
    bin: 'БСН',
    fullName: 'Аты-жөні',
    passwordLabel: 'Құпия сөз',
    depositAmount: 'Депозитті толтыру сомасы (₸)',
    cancel: 'Болдырмау',
    createClient: 'Клиентті құру',
    creating: 'Құрылуда...',
    topUpDeposit: 'Депозитті толтыру',
    topUpAmount: 'Толықтыру сомасы (₸)',
    paymentMethod: 'Төлем әдісі',
    bankCard: 'Банк картасы (Kaspi, Halyk)',
    pay: 'Төлеу',
    processing: 'Өңделуде...',
    topUp: 'Толықтыру',
    myShipments: 'Мои отправки',
    myShipmentsDesc: 'Управление корпоративными перевозками',
    activeShipments: 'Активные отправки',
    pendingPickup: 'Ожидают забора',
    totalThisMonth: 'Всего за месяц',
    avgDeliveryTime: 'Среднее время доставки',
    days: 'дней',
    createNewShipment: 'Создать отправку',
    recentShipments: 'Недавние отправки',
    viewAll: 'Посмотреть все',
    deposit: 'Депозит',
    thisMonth: 'За месяц',
    documents: 'Документы',
    generateDocuments: 'Сформировать документы',
    invoice: 'Счёт-фактура',
    actOfWork: 'Акт выполненных работ',

    waybillRegistry: 'Реестр накладных',

    // Individual Dashboard
    individualDashboard: 'Жеке кабинет',
    myBaggage: 'Менің багаждым',
    myBaggageDesc: 'Жөнелтулерді көзделу',
    trackShipment: 'Жөнелтуді көзделу',
    trackingNumber: 'Жөнелту нөмірі',
    enterTrackingNumber: 'Жөнелту нөмірін енгізіңіз',
    track: 'Көзделу',
    noShipmentsYet: 'Жөнелтулеріңіз жетіп келген жок',
    createFirstShipment: 'Бірінші жөнелтуді жасаңыз',

    // Receiver Dashboard
    receiverDashboard: 'Қабылдаушы панелі',
    baggageIssuance: 'Багажды беру',
    baggageIssuanceDesc: 'Багажды беруді басқару',
    readyForPickup: 'Қабылдауға дайын',
    issuedToday: 'Бүгін берілген',
    notifiedClients: 'Клиенттерге хабарландырылды',
    avgWaitTime: 'Орта күту уақыты',
    minutes: 'минут',
    scanOrEnter: 'Сканерлеу немесе енгізу',
    scanQrOrEnter: 'QR-кодты сканерлеу немесе жөнелту нөмірін енгізу',
    shipmentNumber: 'Жөнелту нөмірі',
    enterShipmentNumber: 'Жөнелту нөмірін енгізіңіз',
    findShipment: 'Жөнелтуді табу',
    readyForIssue: 'Беру үшін дайын',
    issueToClient: 'Клиентке беру',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ru] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}