import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en' | 'kk';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ru: {
    // Top Bar
    headerStation: 'Станция Алматы-1',
    search: 'Поиск',
    systemNameDesc: 'Система управления грузоперевозками',
    clientRegistration: 'Регистрация клиента',
    forIndividualAndCorporate: 'Для физических и корпоративных клиентов',
    login: 'Вход в систему',
    selectClientFrom: 'Выберите клиента из',
    selectClient: 'Выберите клиента...',
    enterClientNameHint: 'Введите ФИО или название организации...',
    noClientsFound: 'Клиентов не найдено',
    mandatory: 'Обязательно',
    pickupPlaceholder: 'Например: ул. Абая 12, кв. 5',
    deliveryPlaceholder: 'Например: пр. Достык 88, офис 301',
    errorSameStation: 'Пункты отправления и назначения не могут совпадать.',
    balance: 'Баланс',
    optional: 'необязательно',
    quantityPlaces: 'Количество мест',
    doorToDoorService: 'Сервис от двери до двери',
    kazakhstan: 'Казахстан',
    russia: 'Россия',
    uzbekistan: 'Узбекистан',
    payFromDeposit: 'Списать с депозита',
    depositAvailable: 'Депозит доступен:',
    depositUnavailable: 'Списание с депозита недоступно. Баланс:',
    insufficientDeposit: 'Недостаточно средств на депозите для списания',
    cash: 'Наличные',
    card: 'Карта',
    sidebarDashboard: 'Дашборд',
    sidebarDoorToDoor: 'До двери',
    sidebarFrequentClients: 'Быстрые клиенты',

    // Manager Dashboard
    managerDashboard: 'Дашборд менеджера',
    manageShipmentsAtStation: 'Управление посылками на станции',
    searchManagerPlaceholder: 'Поиск: номер, клиент, маршрут...',
    newestFirst: 'Новые сначала',
    oldestFirst: 'Старые сначала',
    expensiveFirst: 'Дороже сначала',
    cheapestFirst: 'Дешевле сначала',
    allStatuses: 'Все статусы',
    statusRegisteredDoor: 'Оформлено (до двери)',
    statusWaitingCourier: 'Ожидает курьера',
    statusCourierDriving: 'Курьер едет',
    statusCargoPickedUp: 'Груз забран',
    statusInWagon: 'В вагоне',
    resetFilters: 'Сбросить фильтры',
    totalShipmentsCount: 'Всего: {{count}} посылок',
    tabDoorToDoor: 'До двери',
    tabWaitingPickup: 'Ожидают привоза',
    tabActive: 'Активные',
    tabArrival: 'Прибытие',
    tabTransit: 'В пути',
    noTasks: 'Нет задач',
    noWaiting: 'Нет ожидающих',
    noActive: 'Нет активных',
    legalWaitingPickup: 'Юрлицо: ожидаем привоз',
    readyForLoading: 'Готов к погрузке',
    surchargeRequired: 'Доплата требуется',
    call: 'Позвонить',
    stationLabel: 'Станция',
    notificationTitle: 'Уведомления',
    noNotifications: 'Нет новых уведомлений',
    logoutTitle: 'Выход',
    instructionsTitle: 'Инструкция',
    notificationDetails: 'Детали уведомления',
    openShipment: 'Открыть груз',
    close: 'Закрыть',
    printTitle: 'Печать',
    weightLabel: 'Вес:',
    placeLabel: 'Место:',
    of: 'из',
    kg: 'кг',
    locale: 'ru-RU',

    // Payment Log
    paymentLog: 'Журнал оплат',
    paymentLogDesc: 'История всех транзакций и оплат по отправлениям',
    amount: 'Сумма',
    paymentMethod: 'Способ оплаты',
    shipmentNumberLabel: 'Номер отправки',
    confirmed: 'Подтвержден',
    pending: 'Ожидает',
    noPaymentRecords: 'Нет записей об оплатах.',

    // Audit Log
    userActions: 'Действия пользователей и системные события',
    searchLogs: 'Поиск по логам...',
    event: 'Событие',
    source: 'Источник (Платформа)',
    noLogs: 'Логи не найдены',
    system: 'Система',
    clientRole: 'Клиент',
    courierRole: 'Курьер',
    receiverRole: 'Приемосдатчик',
    managerRole: 'Менеджер',
    shipmentEntity: 'посылку',
    genericEntity: 'сущность',
    actionCreated: 'оформил',
    actionTookWork: 'взял в работу',
    actionPickedUp: 'забрал у клиента',
    actionStationIntake: 'сдал на склад',
    actionPayment: 'провел оплату за',
    actionLoaded: 'погрузил',
    actionArrived: 'принял на станции',
    actionQR: 'сгенерировал QR-код для',
    actionExecuted: 'выполнил',
    platformCourier: 'Приложение Курьера',
    platformReceiver: 'Терминал Приемосдатчика',
    platformClient: 'Личный кабинет клиента',
    platformDashboard: 'Панель управления',
    statusChangedTo: 'Изменен статус на:',

    // Frequent Clients
    frequentClients: 'Быстрые клиенты',
    frequentClientsDesc: 'Клиентская база для Glovo, Choko и других компаний',
    addClient: 'Добавить клиента',
    otherCompany: 'Другая компания',
    otherCompanies: 'Другие компании',
    companyName: 'Название компании',
    clientFullName: 'ФИО клиента',
    contractNumber: 'Номер договора',
    notes: 'Комментарий',
    saving: 'Сохраняем...',
    clientList: 'Список клиентов',
    noRecords: 'Нет записей',
    noExtraData: 'Без доп. данных',
    errorLoadFrequent: 'Не удалось загрузить быстрых клиентов',
    errorSaveFrequent: 'Не удалось сохранить клиента',
    provideClientName: 'Укажите имя клиента',
    provideCompanyName: 'Для "Другая компания" укажите название компании',

    // Receiver Dashboard
    receiverPanel: 'Приемосдатчик',
    stationNotSpecified: 'Станция не указана',
    shiftLog: 'Журнал смены',
    logEmpty: 'Журнал пуст',
    scanLogic: 'Логика сканирования',
    onWarehouse: 'НА СКЛАДЕ',
    yourStationDeparture: '+ ваша станция = отправление',
    yourStationDestination: '+ ваша станция = назначение',
    loaded: 'ПОГРУЖЕН',
    inTransit: 'В ПУТИ',
    arrived: 'ПРИНЯТ',
    weighingCargo: 'Взвешивание груза',
    enterActualWeight: 'Введите фактический вес (заявлено: {declared})',
    actualWeightPlaceholder: 'Фактический вес (например: 15.5)',
    confirmWeight: 'Подтвердить вес',
    scanQrPlaceholder: 'Отсканируйте QR...',
    scanNumberPlaceholder: 'Введите SH-XXXXXX',
    processing: 'Обработка...',
    shipmentLoadedMsg: 'Груз {num} погружен ✓',
    shipmentIntakeMsg: 'Груз {num} принят на склад ✓',
    shipmentArrivedMsg: 'Груз {num} принят ✓',
    scanError: 'Ошибка сканирования',
    networkError: 'Ошибка сети. Проверьте подключение.',
    extraChargeMsg: 'Принято. Клиенту отправлено уведомление о доплате {charge} тг',
    weightConfirmError: 'Ошибка подтверждения веса',
    success: 'УСПЕХ',
    alreadyProcessed: 'УЖЕ ОБРАБОТАН',
    error: 'ОШИБКА',

    // Sidebar
    dashboard: 'Панель управления',
    pages: 'Страницы',
    newShipment: 'Новая отправка',
    activeShipments: 'Активные отправки',
    transit: 'Транзит',
    arrival: 'Прибытие',
    reports: 'Отчёты',
    wms: 'WMS склад',
    settings: 'Настройки',
    userProfile: 'Профиль пользователя',
    corporate: 'Корпоративные клиенты',

    // New Shipment
    newShipmentTitle: 'Новая отправка',
    newShipmentDesc: 'Оформление перевозки багажа',
    clientInfo: 'Информация о клиенте',
    cargoDetails: 'Детали груза',
    payment: 'Оплата',

    // Client Info
    clientType: 'Тип клиента',
    individual: 'Физическое лицо',
    legal: 'Юридическое лицо',
    clientName: 'ФИО / Название организации',
    enterClientName: 'Введите имя клиента',
    clientSource: 'Источник клиента',
    selectSource: 'Выберите источник',
    directContact: 'Прямое обращение',
    contractNumber: 'Номер договора',
    depositSystem: 'Депозитная система',
    route: 'Маршрут',
    from: 'Откуда',
    to: 'Куда',
    selectStation: 'Выберите станцию',
    departureDate: 'Дата отправления',
    transportCost: 'Стоимость перевозки',
    next: 'Далее',
    back: 'Назад',
    receiverName: 'ФИО Получателя',
    enterReceiverName: 'Введите имя получателя',
    receiverPhone: 'Телефон Получателя',
    recipientIsAnotherPerson: 'Получатель — другое лицо',
    doorToDoorDelivery: 'Доставка «До двери»',
    pickupAddress: 'Адрес забора груза',
    deliveryAddress: 'Адрес доставки получателю',
    courierPhone: 'Контактный телефон (для курьера)',
    doorToDoorTitle: 'Заявки «До двери»',
    doorToDoorDesc: 'Управление курьерской доставкой и выездным обслуживанием',
    activeRequests: 'Активные заявки',
    pickupLabel: 'Забор',
    deliveryLabel: 'Доставка',
    noDoorToDoor: 'Нет заявок «До двери»',
    nothingFound: 'Ничего не найдено',
    loading: 'Загрузка...',
    optional: 'необязательно',
    searchByNumberOrClient: 'Поиск по номеру или клиенту...',

    // Cargo Details
    cargoDetailsTitle: 'Детали груза',
    mobiusTicket: 'Проверка билета Mobius',
    hasTicket: 'У клиента есть билет',
    ticketNumber: 'Номер билета',
    ticketDiscount: 'Применена скидка 50% по билету',
    weight: 'Вес (кг)',
    quantityPlaces: 'Количество мест',
    dimensionsPlaceholder: 'Длина × Ширина × Высота',
    cargoValue: 'Ценность груза',
    fragile: 'Хрупкий',
    oversized: 'Негабаритный',
    packaging: 'Упаковка',
    selectPackaging: 'Выберите тип упаковки',
    woodCrate: 'Деревянная обрешётка',
    stretchFilm: 'Стрейч-пленка',
    cardboard: 'Картонная коробка',
    bag: 'Мешок',
    noPackaging: 'Без упаковки',
    declaredValue: 'Объявленная ценность (₸)',
    cargoDescription: 'Описание груза',
    describeContent: 'Опишите содержимое багажа',

    // Payment
    tariffCalculation: 'Расчёт тарифа',
    baseTransportCost: 'Базовая стоимость перевозки:',
    weightSurcharge: 'Доплата за вес:',
    fragileCargo: 'Хрупкий груз:',
    oversizedCargo: 'Негабаритный груз:',
    ticketDiscountLabel: 'Скидка по билету (50%):',
    totalPayment: 'Итого к оплате:',
    emailReceipt: 'Email для чека',
    cardInfo: 'Информация о карте',
    cardholderName: 'Имя держателя карты',
    countryRegion: 'Страна или регион',
    postalCode: 'Индекс',
    payButton: 'Оплатить',
    termsAgree: 'Нажимая "Оплатить", вы соглашаетесь с',
    termsOfUse: 'Условиями использования',
    privacyPolicy: 'Политикой конфиденциальности',
    and: 'и',

    // Active Shipments
    activeShipmentsTitle: 'Активные отправки',
    activeShipmentsDesc: 'Список отправок в обработке',
    searchPlaceholder: 'Поиск по номеру отправки, клиенту...',
    filters: 'Фильтры',
    number: 'Номер',
    client: 'Клиент',
    routeColumn: 'Маршрут',
    weightColumn: 'Вес',
    date: 'Дата',
    status: 'Статус',
    actions: 'Действия',
    details: 'Подробнее',
    inTransit: 'В пути',
    loaded: 'Погружен',
    arrived: 'Прибыл',
    statusPaid: 'Оплачено',
    paymentPending: 'Ожидает оплаты',

    // Shipment Details
    mainInfo: 'Основная информация',
    routeInfo: 'Маршрут',
    receiverOther: 'Получатель (другое лицо)',
    cargoParams: 'Параметры груза',
    downloadWaybill: 'Скачать накладную',
    downloadSurrenderList: 'Скачать сдаточный список',
    statusPickup: 'Забор',
    statusDelivery: 'Доставка',
    statusWaiting: 'Ожидает',
    statusInWork: 'В работе',
    statusDoorToDoor: 'От дома до дома',

    // Transit
    transitTitle: 'Транзит',
    transitDesc: 'Регистрация перемещения багажа',
    qrScanning: 'Сканирование QR-кода',
    scanQrDesc: 'Отсканируйте QR-код на багаже для регистрации',
    startScanning: 'Начать сканирование',
    recentScans: 'Последние сканирования',
    transitLoading: 'Погрузка',
    arrivalScan: 'Прибытие',
    issuance: 'Выдача',
    action: 'Действие',

    // Arrival
    arrivalTitle: 'Прибытие',
    arrivalDesc: 'Управление прибывшим багажом',
    arrivedShipments: 'Прибывшие отправки',
    notifyAll: 'Уведомить всех',
    notified: 'Уведомлен',
    arrivedFrom: 'Откуда:',
    arrivedAt: 'Прибыл:',
    phone: 'Телефон:',
    notify: 'Уведомить',
    issue: 'Выдать',
    scanForIssue: 'Сканирование груза для выдачи',
    barcodePlaceholder: 'Считайте штрих-код сканером...',
    noArrivals: 'Нет грузов, ожидающих выдачи',
    issueBaggage: 'Выдача груза',
    recipientName: 'Имя получателя',
    fullNameByDoc: 'ФИО по документу',
    recipientPhone: 'Телефон получателя',
    phonePlaceholder: '+7 (___) ___-__-__',
    errorProvideNamePhone: 'Укажите имя и телефон',
    errorSurchargeNeeded: 'Сначала необходимо получить доплату',
    errorReceiverMismatch: 'Данные получателя не совпадают. Укажите правильное имя и телефон.',
    scanSuccess: 'Груз успешно просканирован',
    scanError: 'Ошибка сканирования',

    // Reports
    reportsTitle: 'Отчёты',
    reportsDesc: 'Формирование и просмотр отчетов',
    fo3Report: 'Отчёт FO-3',
    financialReport: 'Финансовый отчёт',
    shipmentsReport: 'Отчёт по отправкам',
    generalStats: 'Общая статистика',
    auditLog: 'Журнал аудита',
    userActions: 'Действия пользователей',
    routeReport: 'Отчёт по маршрутам',
    routeAnalysis: 'Анализ направлений',
    allUsers: 'Все пользователи',
    allRoutes: 'Все маршруты',
    generate: 'Сформировать',
    export: 'Выгрузить',

    // WMS
    wmsTitle: 'WMS склад',
    wmsDesc: 'Автоматизированная система складских ячеек',
    storageCells: 'Складские ячейки',
    cellStatus: 'Статус ячеек',
    free: 'Свободно',
    occupied: 'Занято',
    maintenance: 'Обслуживание',
    selfService: 'Самообслуживание',
    selfServiceDesc: 'Сдача багажа без участия оператора',
    scanDocument: 'Сканировать документ',
    scanDocumentDesc: 'Отсканируйте паспорт или QR-код для начала',
    placeInCell: 'Поместите багаж в ячейку',
    placeInCellDesc: 'Откройте ячейку и поместите багаж внутрь',
    autoMeasure: 'Автоматическое измерение',
    autoMeasureDesc: 'Вес и габариты будут измерены автоматически',
    confirmShipment: 'Подтвердите отправку',
    confirmShipmentDesc: 'Проверьте данные и получите QR-код',
    cellNumber: 'Ячейка',
    openCell: 'Открыть ячейку',
    closeCell: 'Закрыть ячейку',

    // Settings
    settingsTitle: 'Настройки',
    settingsDesc: 'Настройки системы и профиля',
    languageSettings: 'Язык интерфейса',
    themeSettings: 'Тема оформления',
    light: 'Светлая',
    dark: 'Тёмная',
    notificationSettings: 'Уведомления',
    emailNotifications: 'Email уведомления',
    smsNotifications: 'SMS уведомления',
    saveSettings: 'Сохранить настройки',

    // Common
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    close: 'Закрыть',
    save: 'Сохранить',
    delete: 'Удалить',
    edit: 'Редактировать',

    // Shipment created
    shipmentCreated: 'Отправка создана',
    documentsReady: 'Документы сформированы и готовы к печати',
    printDocuments: 'Печать документов',
    newShipmentButton: 'Новая отправка',

    // Manager Dashboard
    managerDashboard: 'Панель менеджера',
    managerDashboardDesc: 'Аналитика и статистика работы системы',
    monthlyShipments: 'Запланировано перевозок',
    completedShipments: 'Выполнено перевозок',
    activeContracts: 'Активных договоров',
    wagonsInWork: 'Вагонов в работе',
    month: 'Месяц',
    active: 'Активные',
    total: 'Всего',
    vsLastMonth: 'к прошлому месяцу',
    planCompletion: 'выполнения плана',
    newPerWeek: 'новых за неделю',
    withCargo: 'под грузом',
    routeAnalysisTitle: 'Анализ маршрутов',
    topRoutes: 'Топ маршрутов',
    shipments: 'отправок',
    wagonStatusTitle: 'Статус вагонов',
    underCargo: 'Под грузом',
    atStation: 'На станции',
    inIdle: 'В простое',
    empty: 'Порожний',
    inRepair: 'В ремонте',
    financialMetrics: 'Финансовые показатели',
    revenue: 'Выручка',
    expenses: 'Расходы',
    profit: 'Прибыль',
    currentMonth: 'Текущий месяц',
    thisMonth: 'В этом месяце',
    thisQuarter: 'В этом квартале',
    revenueByRoute: 'Выручка по направлениям',
    totalRevenue: 'Общая выручка',
    wagonsByStatus: 'Вагоны по статусу',
    wagons: 'вагонов',

    plannedActual: 'Плановые и фактические показатели',
    positiveTrend: 'Положительная динамика',
    halfYearPlan: 'План на полугодие',
    actualRevenue: 'Фактическая выручка',
    planExecution: 'Выполнение плана',
    planned: 'Запланировано',
    actual: 'Фактически',

    // Admin Dashboard
    adminDashboard: 'Панель администратора',
    employeeManagement: 'Управление сотрудниками',
    employeeManagementDesc: 'Создание и управление учётными записями',
    totalEmployees: 'Всего сотрудников',
    activeEmployees: 'Активных',
    operators: 'Менеджеры',
    receivers: 'Приёмщики',
    createEmployee: 'Создать сотрудника',
    name: 'Имя',
    email: 'Email',
    role: 'Роль',
    station: 'Станция',
    createdAt: 'Создан',
    statusEmployee: 'Статус',
    actionsEmployee: 'Действия',
    createNewEmployee: 'Создание нового сотрудника',
    fullName: 'Полное имя',
    enterFullName: 'Введите полное имя',
    enterEmail: 'Введите email',
    password: 'Пароль',
    enterPassword: 'Введите пароль',
    operator: 'Менеджер',
    receiver: 'Приёмщик',
    roleAdmin: 'Администратор',
    roleManager: 'Менеджер',
    roleAuditor: 'Ревизор',
    roleMobileGroup: 'Мобильная группа',
    roleTrainReceiver: 'Приемосдатчик в поезде',
    roleDirectionHead: 'Руководитель по направлению',
    roleChiefHead: 'Главный руководитель',
    roleCourier: 'Курьер',


    // Courier Dashboard
    tasksTitle: 'Задачи',
    availableTasks: 'Доступные задачи',
    myTasks: 'Мои задачи',
    noTasks: 'Нет задач',
    pickupType: 'Забор',
    deliveryType: 'Доставка',
    addressNotSpecified: 'Адрес не указан',
    activeBadge: 'Активен',
    noStation: 'Нет станции',
    takeTask: 'Взять задание',
    deliveredToReceiver: 'Доставил получателю',
    pickedUpFromClient: 'Забрал у клиента',
    handOverToStation: 'Сдайте на станцию',
    callClient: 'Позвонить',
    open2Gis: 'Открыть в 2ГИС',
    courierStatusWaitingPickup: 'Ожидает забора',
    courierStatusAssigned: 'Вы едете к клиенту',
    courierStatusPickedUp: 'У вас (сдать на станцию)',
    courierStatusWaitingDelivery: 'Ожидает доставки',
    courierStatusDelivered: 'Доставлено',
    courierStatusLoaded: 'Сдано на станцию',


    // ActiveShipmentDetails
    created: 'Создано',
    printLabels: 'Печать наклеек',
    doorToDoorAddresses: 'Адреса «До двери»',
    qrForScanner: 'QR-код для ТСД',
    pcs: 'шт',
    contactPhone: 'Контактный телефон',
    readyStatus: 'По готовности',

    // Shipment statuses (IndividualDashboard)
    statusRegistered: 'Оформлен',
    statusLoaded: 'Погружен',
    statusInTransit: 'В пути',
    statusArrived: 'Прибыл',
    statusReadyForIssue: 'Готов к выдаче',
    statusIssued: 'Выдан',
    clickForDetails: 'Нажмите для подробностей',
    myShipments: 'Мои посылки',
    createButton: 'Создать',
    searchByNameEmail: 'Поиск по имени, email или станции...',
    newEmployee: 'Новый сотрудник',
    employeeCreatedSuccess: 'Сотрудник успешно создан!',
    deleteEmployeeConfirm: 'Вы уверены, что хотите удалить этого сотрудника?',
    employeeLabel: 'Сотрудник',
    dateCreated: 'Дата создания',
    activeStatus: 'Активен',
    inactiveStatus: 'Неактивен',
    noEmployeesFound: 'Сотрудники не найдеы',

    // Corporate Dashboard
    corporateDashboard: 'Корпоративная панель',
    corporateClientsDesc: 'Управление юридическими лицами',
    addClient: 'Добавить клиента',
    searchByNameOrContract: 'Поиск по названию, договору...',
    noCorporateClients: 'Нет корпоративных клиентов.',
    withoutName: 'Без названия',
    activeCount: 'активных',
    binContract: 'БИН/Договор:',
    contactPerson: 'Контактное лицо:',
    depositSumMsg: 'Сумма пополнения (₸):',
    addCorporateClient: 'Добавить корпоративного клиента',
    companyName: 'Название компании',
    bin: 'БИН',
    // fullName: 'ФИО',
    passwordLabel: 'Пароль',
    depositAmount: 'Сумма пополнения депозита (₸)',
    // cancel: 'Отмена',
    createClient: 'Создать клиента',
    creating: 'Создание...',
    topUpDeposit: 'Пополнить депозит',
    topUpAmount: 'Сумма пополнения (₸)',
    paymentMethod: 'Способ оплаты',
    bankCard: 'Банковская карта (Kaspi, Halyk)',
    pay: 'Оплатить',
    processing: 'Обработка...',
    topUp: 'Пополнить',
    myShipmentsDesc: 'Управление корпоративными перевозками',

    pendingPickup: 'Ожидают забора',
    totalThisMonth: 'Всего за месяц',
    avgDeliveryTime: 'Среднее время доставки',
    days: 'дней',
    createNewShipment: 'Создать отправку',
    recentShipments: 'Недавние отправки',
    viewAll: 'Посмотреть все',
    deposit: 'Депозит',
    thisMonthLabel: 'За месяц',
    documents: 'Документы',
    generateDocuments: 'Сформировать документы',
    invoice: 'Счёт-фактура',
    actOfWork: 'Акт выполненных работ',

    waybillRegistry: 'Реестр накладных',

    // Individual Dashboard
    individualDashboard: 'Личный кабинет',
    myBaggage: 'Мой багаж',
    myBaggageDesc: 'Отслеживание отправок',
    trackShipment: 'Отследить отправку',
    trackingNumber: 'Номер отправки',
    enterTrackingNumber: 'Введите номер отправки',
    track: 'Отследить',
    noShipmentsYet: 'У вас пока нет отправок',
    createFirstShipment: 'Создайте свою первую отправку',

    // Receiver Dashboard
    receiverDashboard: 'Панель приёмщика',
    baggageIssuance: 'Выдача багажа',
    baggageIssuanceDesc: 'Управление выдачей багажа',
    readyForPickup: 'Готово к выдаче',
    issuedToday: 'Выдано сегодня',
    notifiedClients: 'Уведомлено клиентов',
    avgWaitTime: 'Среднее время ожидания',
    minutes: 'минут',
    scanOrEnter: 'Сканировать или ввести номер',
    scanQrOrEnter: 'Отсканируйте QR-код или введите номер отправки',
    shipmentNumber: 'Номер отправки',
    enterShipmentNumber: 'Введите номер отправки',
    findShipment: 'Найти отправку',
    readyForIssue: 'Готово к выдаче',
    issueToClient: 'Выдать клиенту',

    paymentLog: 'Журнал оплат',
    paymentLogDesc: 'История оплат',
    totalSum: 'Итоговая сумма',
    confirmDeleteClient: 'Вы уверены, что хотите удалить этого клиента?',

    // Receiver Tabs
    loadingPlan: 'План',
    arrivalTab: 'Прибытие',
    auditTab: 'Журнал',
    searchLogs: 'Поиск по ID груза, действию...',
    noLogs: 'Нет записей в журнале.',
    entity: 'Сущность',
    newValue: 'Новое значение: ',
    noCargoToLoad: 'Нет грузов для погрузки',
    scanQrPlaceholder: 'Сканируй QR-код...',
    loadButton: 'Погрузить',

    // Mobile Group (AuditorTerminal)
    logoutBtn: 'Выход',
    networkError: 'Ошибка сети',
    mobileGroupReady: 'Готов к сканированию',
    mobileGroupTitle: 'Мобильная группа',
    mobileGroupSubtitle: 'Станция',
    mobileGroupStationNotSet: 'Станция не задана',
    mobileGroupChecked: 'Проверено',
    mobileGroupApproved: 'Одобрено',
    mobileGroupRejected: 'Отклонено',
    mobileGroupMismatch: 'Несовп. станции',
    mobileGroupShift: 'Смена',
    mobileGroupScanTitle: 'Сканирование груза',
    mobileGroupScanDesc: 'Введите номер отправки вручную или используйте сканер штрихкода — нажмите Enter для проверки',
    mobileGroupScanPlaceholder: 'Наведите сканер или введите номер...',
    mobileGroupChecking: 'Проверка...',
    mobileGroupCheckButton: 'Проверить груз',
    mobileGroupReadOnly: 'Режим только чтения — статус груза не изменяется',
    mobileGroupHistory: 'Журнал проверок',
    mobileGroupSuccess: 'УСПЕХ',
    mobileGroupError: 'ОШИБКА',
    mobileGroupRoute: 'Маршрут:',
    mobileGroupCurrentStation: 'Текущая станция:',
  },

  en: {
    // Top Bar
    headerStation: 'Almaty-1 Station',
    search: 'Search',
    systemNameDesc: 'Cargo Management System',
    clientRegistration: 'Client Registration',
    forIndividualAndCorporate: 'For individual and corporate clients',
    login: 'Login',
    selectClientFrom: 'Select client from',
    selectClient: 'Select client...',
    enterClientNameHint: 'Enter full name or organization name...',
    noClientsFound: 'No clients found',
    mandatory: 'Mandatory',
    pickupPlaceholder: 'Example: 12 Abay St, Apt 5',
    deliveryPlaceholder: 'Example: 88 Dostyk Ave, Office 301',
    errorSameStation: 'Departure and destination stations cannot be the same.',
    balance: 'Balance',
    optional: 'optional',
    quantityPlaces: 'Number of places',
    doorToDoorService: 'Door to door service',
    kazakhstan: 'Kazakhstan',
    russia: 'Russia',
    uzbekistan: 'Uzbekistan',
    payFromDeposit: 'Pay from deposit',
    depositAvailable: 'Deposit available:',
    depositUnavailable: 'Deposit withdrawal unavailable. Balance:',
    insufficientDeposit: 'Insufficient funds on deposit',
    cash: 'Cash',
    card: 'Card',
    sidebarDashboard: 'Dashboard',
    sidebarDoorToDoor: 'Door to Door',
    sidebarFrequentClients: 'Frequent Clients',

    // Manager Dashboard
    managerDashboard: 'Manager Dashboard',
    manageShipmentsAtStation: 'Manage shipments at station',
    searchManagerPlaceholder: 'Search: number, client, route...',
    newestFirst: 'Newest first',
    oldestFirst: 'Oldest first',
    expensiveFirst: 'Most expensive first',
    cheapestFirst: 'Cheapest first',
    allStatuses: 'All statuses',
    statusRegisteredDoor: 'Registered (door-to-door)',
    statusWaitingCourier: 'Waiting for courier',
    statusCourierDriving: 'Courier is driving',
    statusCargoPickedUp: 'Cargo picked up',
    statusInWagon: 'In wagon',
    resetFilters: 'Reset filters',
    totalShipmentsCount: 'Total: {{count}} shipments',
    tabDoorToDoor: 'Door to Door',
    tabWaitingPickup: 'Waiting for Pickup',
    tabActive: 'Active',
    tabArrival: 'Arrival',
    tabTransit: 'In Transit',
    noTasks: 'No tasks',
    noWaiting: 'No waiting shipments',
    noActive: 'No active shipments',
    legalWaitingPickup: 'Legal entity: waiting for pickup',
    readyForLoading: 'Ready for loading',
    surchargeRequired: 'Surcharge required',
    call: 'Call',
    stationLabel: 'Station',
    notificationTitle: 'Notifications',
    noNotifications: 'No new notifications',
    logoutTitle: 'Logout',
    instructionsTitle: 'Instructions',
    notificationDetails: 'Notification details',
    openShipment: 'Open shipment',
    close: 'Close',
    printTitle: 'Print',
    weightLabel: 'Weight:',
    placeLabel: 'Place:',
    of: 'of',
    kg: 'kg',
    locale: 'en-US',

    // Payment Log
    paymentLog: 'Payment Log',
    paymentLogDesc: 'History of all transactions and shipment payments',
    amount: 'Amount',
    paymentMethod: 'Payment Method',
    shipmentNumberLabel: 'Shipment Number',
    confirmed: 'Confirmed',
    pending: 'Pending',
    noPaymentRecords: 'No payment records found.',

    // Audit Log
    userActions: 'User actions and system events',
    searchLogs: 'Search logs...',
    event: 'Event',
    source: 'Source (Platform)',
    noLogs: 'No logs found',
    system: 'System',
    clientRole: 'Client',
    courierRole: 'Courier',
    receiverRole: 'Receiver',
    managerRole: 'Manager',
    shipmentEntity: 'shipment',
    genericEntity: 'entity',
    actionCreated: 'created',
    actionTookWork: 'took in work',
    actionPickedUp: 'picked up from client',
    actionStationIntake: 'delivered to warehouse',
    actionPayment: 'processed payment for',
    actionLoaded: 'loaded',
    actionArrived: 'received at station',
    actionQR: 'generated QR-code for',
    actionExecuted: 'executed',
    platformCourier: 'Courier App',
    platformReceiver: 'Receiver Terminal',
    platformClient: 'Client Dashboard',
    platformDashboard: 'Management Panel',
    statusChangedTo: 'Status changed to:',

    // Frequent Clients
    frequentClients: 'Frequent Clients',
    frequentClientsDesc: 'Client base for Glovo, Choko and other companies',
    addClient: 'Add Client',
    otherCompany: 'Other company',
    otherCompanies: 'Other companies',
    companyName: 'Company Name',
    clientFullName: 'Client Full Name',
    contractNumber: 'Contract Number',
    notes: 'Notes',
    saving: 'Saving...',
    clientList: 'Client List',
    noRecords: 'No records',
    noExtraData: 'No extra data',
    errorLoadFrequent: 'Failed to load frequent clients',
    errorSaveFrequent: 'Failed to save client',
    provideClientName: 'Provide client name',
    provideCompanyName: 'For "Other company" provide company name',

    // Receiver Dashboard
    receiverPanel: 'Receiver',
    stationNotSpecified: 'Station not specified',
    shiftLog: 'Shift Log',
    logEmpty: 'Log is empty',
    scanLogic: 'Scan Logic',
    onWarehouse: 'AT WAREHOUSE',
    yourStationDeparture: '+ your station = departure',
    yourStationDestination: '+ your station = destination',
    loaded: 'LOADED',
    inTransit: 'IN TRANSIT',
    arrived: 'ARRIVED',
    weighingCargo: 'Weighing Cargo',
    enterActualWeight: 'Enter actual weight (declared: {declared})',
    actualWeightPlaceholder: 'Actual weight (e.g.: 15.5)',
    confirmWeight: 'Confirm Weight',
    scanQrPlaceholder: 'Scan QR...',
    scanNumberPlaceholder: 'Enter SH-XXXXXX',
    processing: 'Processing...',
    shipmentLoadedMsg: 'Shipment {num} loaded ✓',
    shipmentIntakeMsg: 'Shipment {num} at warehouse ✓',
    shipmentArrivedMsg: 'Shipment {num} arrived ✓',
    scanError: 'Scan error',
    networkError: 'Network error. Check connection.',
    extraChargeMsg: 'Accepted. Client notified about extra charge {charge} ₸',
    weightConfirmError: 'Weight confirmation error',
    success: 'SUCCESS',
    alreadyProcessed: 'ALREADY PROCESSED',
    error: 'ERROR',

    // Sidebar
    dashboard: 'Dashboard',
    pages: 'Pages',
    newShipment: 'New Shipment',
    activeShipments: 'Active Shipments',
    transit: 'Transit',
    arrival: 'Arrival',
    reports: 'Reports',
    wms: 'WMS Warehouse',
    settings: 'Settings',
    userProfile: 'User Profile',
    corporate: 'Corporate Clients',

    // New Shipment
    newShipmentTitle: 'New Shipment',
    newShipmentDesc: 'Baggage transportation registration',
    clientInfo: 'Client Information',
    cargoDetails: 'Cargo Details',
    payment: 'Payment',

    // Client Info
    clientType: 'Client Type',
    individual: 'Individual',
    legal: 'Legal Entity',
    clientName: 'Full Name / Organization Name',
    enterClientName: 'Enter client name',
    clientSource: 'Client Source',
    selectSource: 'Select source',
    directContact: 'Direct Contact',
    contractNumber: 'Contract Number',
    depositSystem: 'Deposit System',
    route: 'Route',
    from: 'From',
    to: 'To',
    selectStation: 'Select station',
    departureDate: 'Departure Date',
    transportCost: 'Transport Cost',
    next: 'Next',
    back: 'Back',
    receiverName: 'Receiver Name',
    enterReceiverName: 'Enter receiver name',
    receiverPhone: 'Receiver Phone',
    recipientIsAnotherPerson: 'Recipient is another person',
    doorToDoorDelivery: 'Door-to-Door Delivery',
    pickupAddress: 'Pickup Address',
    deliveryAddress: 'Delivery Address',
    courierPhone: 'Contact Phone (for courier)',
    doorToDoorTitle: 'Door-to-Door Requests',
    doorToDoorDesc: 'Manage courier delivery and on-site services',
    activeRequests: 'Active Requests',
    pickupLabel: 'Pickup',
    deliveryLabel: 'Delivery',
    noDoorToDoor: 'No door-to-door requests',
    nothingFound: 'Nothing found',
    loading: 'Loading...',
    optional: 'optional',
    searchByNumberOrClient: 'Search by number or client...',

    // Cargo Details
    cargoDetailsTitle: 'Cargo Details',
    mobiusTicket: 'Mobius Ticket Check',
    hasTicket: 'Customer has a ticket',
    ticketNumber: 'Ticket Number',
    ticketDiscount: '50% discount applied with ticket',
    weight: 'Weight (kg)',
    quantityPlaces: 'Number of places',
    dimensionsPlaceholder: 'Length × Width × Height',
    cargoValue: 'Cargo Value',
    fragile: 'Fragile',
    oversized: 'Oversized',
    packaging: 'Packaging',
    selectPackaging: 'Select packaging type',
    woodCrate: 'Wooden Crate',
    stretchFilm: 'Stretch Film',
    cardboard: 'Cardboard Box',
    bag: 'Bag',
    noPackaging: 'No Packaging',
    declaredValue: 'Declared Value (₸)',
    cargoDescription: 'Cargo Description',
    describeContent: 'Describe baggage contents',

    // Payment
    tariffCalculation: 'Tariff Calculation',
    baseTransportCost: 'Base transport cost:',
    weightSurcharge: 'Weight surcharge:',
    fragileCargo: 'Fragile cargo:',
    oversizedCargo: 'Oversized cargo:',
    ticketDiscountLabel: 'Ticket discount (50%):',
    totalPayment: 'Total payment:',
    emailReceipt: 'Email for receipt',
    cardInfo: 'Card Information',
    cardholderName: 'Cardholder Name',
    countryRegion: 'Country or Region',
    postalCode: 'Postal Code',
    payButton: 'Pay',
    termsAgree: 'By clicking "Pay", you agree to',
    termsOfUse: 'Terms of Use',
    privacyPolicy: 'Privacy Policy',
    and: 'and',

    // Active Shipments
    activeShipmentsTitle: 'Active Shipments',
    activeShipmentsDesc: 'List of shipments in progress',
    searchPlaceholder: 'Search by shipment number, client...',
    filters: 'Filters',
    number: 'Number',
    client: 'Client',
    routeColumn: 'Route',
    weightColumn: 'Weight',
    date: 'Date',
    status: 'Status',
    actions: 'Actions',
    details: 'Details',
    inTransit: 'In Transit',
    loaded: 'Loaded',
    arrived: 'Arrived',
    statusPaid: 'Paid',
    paymentPending: 'Payment Pending',

    // Shipment Details
    mainInfo: 'Main Information',
    routeInfo: 'Route',
    receiverOther: 'Receiver (other person)',
    cargoParams: 'Cargo Parameters',
    downloadWaybill: 'Download Waybill',
    downloadSurrenderList: 'Download Surrender List',
    statusPickup: 'Pickup',
    statusDelivery: 'Delivery',
    statusWaiting: 'Waiting',
    statusInWork: 'In Progress',
    statusDoorToDoor: 'Door to Door',

    // Transit
    transitTitle: 'Transit',
    transitDesc: 'Baggage movement registration',
    qrScanning: 'QR Code Scanning',
    scanQrDesc: 'Scan the QR code on baggage for registration',
    startScanning: 'Start Scanning',
    recentScans: 'Recent Scans',
    transitLoading: 'Loading',
    arrivalScan: 'Arrival',
    issuance: 'Issuance',
    action: 'Action',

    // Arrival
    arrivalTitle: 'Arrival',
    arrivalDesc: 'Arrived baggage management',
    arrivedShipments: 'Arrived Shipments',
    notifyAll: 'Notify All',
    notified: 'Notified',
    arrivedFrom: 'From:',
    arrivedAt: 'Arrived:',
    phone: 'Phone:',
    notify: 'Notify',
    issue: 'Issue',
    scanForIssue: 'Scan cargo for issue',
    barcodePlaceholder: 'Read barcode with scanner...',
    noArrivals: 'No cargo waiting for issue',
    issueBaggage: 'Issue baggage',
    recipientName: 'Recipient name',
    fullNameByDoc: 'Full name by document',
    recipientPhone: 'Recipient phone',
    phonePlaceholder: '+7 (___) ___-__-__',
    errorProvideNamePhone: 'Provide name and phone',
    errorSurchargeNeeded: 'Surcharge payment required first',
    errorReceiverMismatch: 'Recipient data mismatch. Provide correct name and phone.',
    scanSuccess: 'Cargo scanned successfully',
    scanError: 'Scanning error',

    // Reports
    reportsTitle: 'Reports',
    reportsDesc: 'Report generation and viewing',
    fo3Report: 'FO-3 Report',
    financialReport: 'Financial Report',
    shipmentsReport: 'Shipments Report',
    generalStats: 'General Statistics',
    auditLog: 'Audit Log',
    userActions: 'User Actions',
    routeReport: 'Route Report',
    routeAnalysis: 'Route Analysis',
    allUsers: 'All Users',
    allRoutes: 'All Routes',
    generate: 'Generate',
    export: 'Export',

    // WMS
    wmsTitle: 'WMS Warehouse',
    wmsDesc: 'Automated storage cell system',
    storageCells: 'Storage Cells',
    cellStatus: 'Cell Status',
    free: 'Free',
    occupied: 'Occupied',
    maintenance: 'Maintenance',
    selfService: 'Self-Service',
    selfServiceDesc: 'Baggage drop-off without operator',
    scanDocument: 'Scan Document',
    scanDocumentDesc: 'Scan passport or QR code to start',
    placeInCell: 'Place in Cell',
    placeInCellDesc: 'Open cell and place baggage inside',
    autoMeasure: 'Auto Measurement',
    autoMeasureDesc: 'Weight and dimensions will be measured automatically',
    confirmShipment: 'Confirm Shipment',
    confirmShipmentDesc: 'Check data and receive QR code',
    cellNumber: 'Cell',
    openCell: 'Open Cell',
    closeCell: 'Close Cell',

    // Settings
    settingsTitle: 'Settings',
    settingsDesc: 'System and profile settings',
    languageSettings: 'Interface Language',
    themeSettings: 'Theme',
    light: 'Light',
    dark: 'Dark',
    notificationSettings: 'Notifications',
    emailNotifications: 'Email Notifications',
    smsNotifications: 'SMS Notifications',
    saveSettings: 'Save Settings',

    // Common
    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',

    // Shipment created
    shipmentCreated: 'Shipment Created',
    documentsReady: 'Documents generated and ready to print',
    printDocuments: 'Print Documents',
    newShipmentButton: 'New Shipment',

    // Manager Dashboard
    managerDashboard: 'Manager Panel',
    managerDashboardDesc: 'Analytics and system performance statistics',
    monthlyShipments: 'Planned shipments',
    completedShipments: 'Completed shipments',
    activeContracts: 'Active contracts',
    wagonsInWork: 'Wagons in work',
    month: 'Month',
    active: 'Active',
    total: 'Total',
    vsLastMonth: 'vs last month',
    planCompletion: 'plan completion',
    newPerWeek: 'new per week',
    withCargo: 'with cargo',
    routeAnalysisTitle: 'Route analysis',
    topRoutes: 'Top routes',
    shipments: 'shipments',
    wagonStatusTitle: 'Wagon status',
    underCargo: 'Under cargo',
    atStation: 'At station',
    inIdle: 'Idle',
    empty: 'Empty',
    inRepair: 'In repair',
    financialMetrics: 'Financial metrics',
    revenue: 'Revenue',
    expenses: 'Expenses',
    profit: 'Profit',
    currentMonth: 'Current month',
    thisMonth: 'This month',
    thisQuarter: 'This quarter',
    revenueByRoute: 'Revenue by route',
    totalRevenue: 'Total revenue',
    wagonsByStatus: 'Wagons by status',
    wagons: 'wagons',

    plannedActual: 'Planned and actual metrics',
    positiveTrend: 'Positive trend',
    halfYearPlan: 'Half-year plan',
    actualRevenue: 'Actual revenue',
    planExecution: 'Plan execution',
    planned: 'Planned',
    actual: 'Actual',

    // Admin Dashboard
    adminDashboard: 'Admin Dashboard',
    employeeManagement: 'Employee Management',
    employeeManagementDesc: 'Create and manage user accounts',
    totalEmployees: 'Total employees',
    activeEmployees: 'Active',
    operators: 'Managers',
    receivers: 'Receivers',
    createEmployee: 'Create employee',
    name: 'Name',
    email: 'Email',
    role: 'Role',
    station: 'Station',
    createdAt: 'Created at',
    statusEmployee: 'Status',
    actionsEmployee: 'Actions',
    createNewEmployee: 'Create new employee',
    fullName: 'Full name',
    enterFullName: 'Enter full name',
    enterEmail: 'Enter email',
    password: 'Password',
    enterPassword: 'Enter password',
    operator: 'Manager',
    receiver: 'Receiver',
    roleAdmin: 'Administrator',
    roleManager: 'Manager',
    roleAuditor: 'Auditor',
    roleMobileGroup: 'Mobile Group',
    roleTrainReceiver: 'Train Receiver',
    roleDirectionHead: 'Direction Head',
    roleChiefHead: 'Chief Head',
    roleCourier: 'Courier',



    // ActiveShipmentDetails
    created: 'Created',
    printLabels: 'Print Labels',
    doorToDoorAddresses: 'Door-to-Door Addresses',
    qrForScanner: 'QR Code for Scanner',
    pcs: 'pcs',
    contactPhone: 'Contact Phone',
    readyStatus: 'On Demand',

    // Courier Dashboard
    tasksTitle: 'Tasks',
    availableTasks: 'Available Tasks',
    myTasks: 'My Tasks',
    noTasks: 'No tasks',
    pickupType: 'Pickup',
    deliveryType: 'Delivery',
    addressNotSpecified: 'Address not specified',
    activeBadge: 'Active',
    noStation: 'No station',
    takeTask: 'Take Task',
    deliveredToReceiver: 'Delivered to Receiver',
    pickedUpFromClient: 'Picked up from Client',
    handOverToStation: 'Hand over to station',
    callClient: 'Call',
    open2Gis: 'Open in 2GIS',
    courierStatusWaitingPickup: 'Waiting for pickup',
    courierStatusAssigned: 'Heading to client',
    courierStatusPickedUp: 'With you (hand over to station)',
    courierStatusWaitingDelivery: 'Waiting for delivery',
    courierStatusDelivered: 'Delivered',
    courierStatusLoaded: 'Handed over to station',

    // Shipment statuses (IndividualDashboard)
    statusRegistered: 'Registered',
    statusLoaded: 'Loaded',
    statusInTransit: 'In Transit',
    statusArrived: 'Arrived',
    statusReadyForIssue: 'Ready for Issue',
    statusIssued: 'Issued',
    clickForDetails: 'Click for details',
    myShipments: 'My Shipments',
    createButton: 'Create',
    searchByNameEmail: 'Search by name, email or station...',
    newEmployee: 'New employee',
    employeeCreatedSuccess: 'Employee successfully created!',
    deleteEmployeeConfirm: 'Are you sure you want to delete this employee?',
    employeeLabel: 'Employee',
    dateCreated: 'Date created',
    activeStatus: 'Active',
    inactiveStatus: 'Inactive',
    noEmployeesFound: 'No employees found',

    // Corporate Dashboard
    corporateDashboard: 'Corporate Dashboard',
    corporateClientsDesc: 'Manage legal entities',
    addClient: 'Add Client',
    searchByNameOrContract: 'Search by name, contract...',
    noCorporateClients: 'No corporate clients.',
    withoutName: 'Unnamed',
    activeCount: 'active',
    binContract: 'BIN/Contract:',
    contactPerson: 'Contact Person:',
    depositSumMsg: 'Deposit Amount (₸):',
    addCorporateClient: 'Add Corporate Client',
    companyName: 'Company Name',
    bin: 'BIN',
    // fullName: 'Full Name',
    passwordLabel: 'Password',
    depositAmount: 'Deposit Top-up Amount (₸)',
    // cancel: 'Cancel',
    createClient: 'Create Client',
    creating: 'Creating...',
    topUpDeposit: 'Top Up Deposit',
    topUpAmount: 'Top-up Amount (₸)',
    paymentMethod: 'Payment Method',
    bankCard: 'Bank Card (Kaspi, Halyk)',
    pay: 'Pay',
    processing: 'Processing...',
    topUp: 'Top Up',
    myShipmentsDesc: 'Manage corporate shipments',

    pendingPickup: 'Pending pickup',
    totalThisMonth: 'Total this month',
    avgDeliveryTime: 'Average delivery time',
    days: 'days',
    createNewShipment: 'Create new shipment',
    recentShipments: 'Recent shipments',
    viewAll: 'View all',
    deposit: 'Deposit',
    thisMonthLabel: 'For the month',
    documents: 'Documents',
    generateDocuments: 'Generate documents',
    invoice: 'Invoice',
    actOfWork: 'Act of work performed',

    waybillRegistry: 'Waybill registry',

    // Individual Dashboard
    individualDashboard: 'Individual Dashboard',
    myBaggage: 'My Baggage',
    myBaggageDesc: 'Track shipments',
    trackShipment: 'Track shipment',
    trackingNumber: 'Tracking number',
    enterTrackingNumber: 'Enter tracking number',
    track: 'Track',
    noShipmentsYet: 'You have no shipments yet',
    createFirstShipment: 'Create your first shipment',

    // Receiver Dashboard
    receiverDashboard: 'Receiver Dashboard',
    baggageIssuance: 'Baggage Issuance',
    baggageIssuanceDesc: 'Manage baggage issuance',
    readyForPickup: 'Ready for pickup',
    issuedToday: 'Issued today',
    notifiedClients: 'Notified clients',
    avgWaitTime: 'Average wait time',
    minutes: 'minutes',
    scanOrEnter: 'Scan or enter number',
    scanQrOrEnter: 'Scan QR code or enter shipment number',
    shipmentNumber: 'Shipment number',
    enterShipmentNumber: 'Enter shipment number',
    findShipment: 'Find shipment',
    readyForIssue: 'Ready for issue',
    issueToClient: 'Issue to client',

    paymentLog: 'Payment Log',
    paymentLogDesc: 'Payment history',
    totalSum: 'Total Sum',
    confirmDeleteClient: 'Are you sure you want to delete this client?',

    // Receiver Tabs
    loadingPlan: 'Plan',
    arrivalTab: 'Arrival',
    auditTab: 'Log',
    searchLogs: 'Search by shipment ID, action...',
    noLogs: 'No logs found.',
    entity: 'Entity',
    newValue: 'New value: ',
    noCargoToLoad: 'No cargo to load',
    scanQrPlaceholder: 'Scan QR code...',
    loadButton: 'Load',

    // Mobile Group (AuditorTerminal)
    logoutBtn: 'Logout',
    networkError: 'Network Error',
    mobileGroupReady: 'Ready to scan',
    mobileGroupTitle: 'Mobile Group',
    mobileGroupSubtitle: 'Station',
    mobileGroupStationNotSet: 'Station not set',
    mobileGroupChecked: 'Checked',
    mobileGroupApproved: 'Approved',
    mobileGroupRejected: 'Rejected',
    mobileGroupMismatch: 'Station mismatch',
    mobileGroupShift: 'Shift',
    mobileGroupScanTitle: 'Cargo scanning',
    mobileGroupScanDesc: 'Enter shipment number manually or use a barcode scanner — press Enter to check',
    mobileGroupScanPlaceholder: 'Point scanner or enter number...',
    mobileGroupChecking: 'Checking...',
    mobileGroupCheckButton: 'Check cargo',
    mobileGroupReadOnly: 'Read-only mode — cargo status is not changed',
    mobileGroupHistory: 'Inspection log',
    mobileGroupSuccess: 'SUCCESS',
    mobileGroupError: 'ERROR',
    mobileGroupRoute: 'Route:',
    mobileGroupCurrentStation: 'Current station:',
  },

  kk: {
    // Top Bar
    headerStation: 'Алматы-1 станциясы',
    search: 'Іздеу',
    systemNameDesc: 'Жүк тасымалдауды басқару жүйесі',
    clientRegistration: 'Клиентті тіркеу',
    forIndividualAndCorporate: 'Жеке және корпоративті клиенттер үшін',
    login: 'Жүйеге кіру',
    selectClientFrom: 'Клиентті таңдаңыз',
    selectClient: 'Клиентті таңдаңыз...',
    enterClientNameHint: 'Аты-жөнін немесе ұйым атауын енгізіңіз...',
    noClientsFound: 'Клиенттер табылмады',
    mandatory: 'Міндетті',
    pickupPlaceholder: 'Мысалы: Абай к-сі 12, 5-пәтер',
    deliveryPlaceholder: 'Мысалы: Достық даңғылы 88, 301-кеңсе',
    errorSameStation: 'Жөнелту және келу станциялары бірдей болмауы керек.',
    balance: 'Теңгерім',
    optional: 'міндетті емес',
    quantityPlaces: 'Орындар саны',
    doorToDoorService: 'Есіктен есікке дейін қызметі',
    kazakhstan: 'Қазақстан',
    russia: 'Ресей',
    uzbekistan: 'Өзбекстан',
    payFromDeposit: 'Депозиттен есептен шығару',
    depositAvailable: 'Депозит қолжетімді:',
    depositUnavailable: 'Депозиттен есептен шығару мүмкін емес. Теңгерім:',
    insufficientDeposit: 'Депозитте есептен шығару үшін қаражат жеткіліксіз',
    cash: 'Қолма-қол ақша',
    card: 'Карта',
    sidebarDashboard: 'Дашборд',
    sidebarDoorToDoor: 'Есікке дейін',
    sidebarFrequentClients: 'Тұрақты клиенттер',

    // Manager Dashboard
    managerDashboard: 'Менеджер дашборды',
    manageShipmentsAtStation: 'Станциядағы жөнелтілімдерді басқару',
    searchManagerPlaceholder: 'Іздеу: нөмірі, клиенті, бағыты...',
    newestFirst: 'Алдымен жаңалары',
    oldestFirst: 'Алдымен ескілері',
    expensiveFirst: 'Алдымен қымбаттары',
    cheapestFirst: 'Алдымен арзандары',
    allStatuses: 'Барлық мәртебелер',
    statusRegisteredDoor: 'Оформлено (есікке дейін)',
    statusWaitingCourier: 'Курьерді күтуде',
    statusCourierDriving: 'Курьер келе жатыр',
    statusCargoPickedUp: 'Жүк алынды',
    statusInWagon: 'Вагонда',
    resetFilters: 'Фильтрлерді тазалау',
    totalShipmentsCount: 'Барлығы: {{count}} сәлемдеме',
    tabDoorToDoor: 'Есікке дейін',
    tabWaitingPickup: 'Әкелуін күтуде',
    tabActive: 'Белсенді',
    tabArrival: 'Келу',
    tabTransit: 'Жолда',
    noTasks: 'Тапсырмалар жоқ',
    noWaiting: 'Күтіп тұрғандар жоқ',
    noActive: 'Белсенділер жоқ',
    legalWaitingPickup: 'Заңды тұлға: әкелуін күтуде',
    readyForLoading: 'Тиеуге дайын',
    surchargeRequired: 'Қосымша төлем қажет',
    call: 'Қоңырау шалу',
    stationLabel: 'Станция',
    notificationTitle: 'Хабарландырулар',
    noNotifications: 'Жаңа хабарландырулар жоқ',
    logoutTitle: 'Шығу',
    instructionsTitle: 'Нұсқаулық',
    notificationDetails: 'Хабарландыру мәліметтері',
    openShipment: 'Жөнелтілімді ашу',
    close: 'Жабу',
    printTitle: 'Басып шығару',
    weightLabel: 'Салмағы:',
    placeLabel: 'Орын:',
    of: '-',
    kg: 'кг',
    locale: 'kk-KZ',

    // Payment Log
    paymentLog: 'Төлемдер журналы',
    paymentLogDesc: 'Барлық транзакциялар мен жөнелтілімдер бойынша төлемдер тарихы',
    amount: 'Салмағы',
    paymentMethod: 'Төлем әдісі',
    shipmentNumberLabel: 'Жөнелту нөмірі',
    confirmed: 'Расталды',
    pending: 'Күтуде',
    noPaymentRecords: 'Төлемдер туралы жазбалар жоқ.',

    // Audit Log
    userActions: 'Пайдаланушы әрекеттері және жүйелік оқиғалар',
    searchLogs: 'Логтар бойынша іздеу...',
    event: 'Оқиға',
    source: 'Дереккөз (Платформа)',
    noLogs: 'Логтар табылмады',
    system: 'Жүйе',
    clientRole: 'Клиент',
    courierRole: 'Курьер',
    receiverRole: 'Приемосдатчик',
    managerRole: 'Менеджер',
    shipmentEntity: 'сәлемдеме',
    genericEntity: 'нысан',
    actionCreated: 'ресімдеді',
    actionTookWork: 'жұмысқа алды',
    actionPickedUp: 'клиенттен алып кетті',
    actionStationIntake: 'қоймаға өткізді',
    actionPayment: 'төлем жасады:',
    actionLoaded: 'тиеді',
    actionArrived: 'станцияда қабылдады',
    actionQR: 'QR-кодты жасады:',
    actionExecuted: 'орындады',
    platformCourier: 'Курьер қосымшасы',
    platformReceiver: 'Приемосдатчик терминалы',
    platformClient: 'Клиенттің жеке кабинеті',
    platformDashboard: 'Басқару панелі',
    statusChangedTo: 'Мәртебесі өзгертілді:',

    // Frequent Clients
    frequentClients: 'Тұрақты клиенттер',
    frequentClientsDesc: 'Glovo, Choko және басқа компаниялар үшін клиенттер базасы',
    addClient: 'Клиент қосу',
    otherCompany: 'Басқа компания',
    otherCompanies: 'Басқа компаниялар',
    companyName: 'Компания атауы',
    clientFullName: 'Клиенттің ТАӘ',
    contractNumber: 'Шарт нөмірі',
    notes: 'Түсініктеме',
    saving: 'Сақталуда...',
    clientList: 'Клиенттер тізімі',
    noRecords: 'Жазбалар жоқ',
    noExtraData: 'Қосымша деректерсіз',
    errorLoadFrequent: 'Тұрақты клиенттерді жүктеу мүмкін болмады',
    errorSaveFrequent: 'Клиентті сақтау мүмкін болмады',
    provideClientName: 'Клиенттің атын көрсетіңіз',
    provideCompanyName: '"Басқа компания" үшін компания атауын көрсетіңіз',

    // Receiver Dashboard
    receiverPanel: 'Приемосдатчик',
    stationNotSpecified: 'Станция көрсетілмеген',
    shiftLog: 'Ауысым журналы',
    logEmpty: 'Журнал бос',
    scanLogic: 'Сканерлеу логикасы',
    onWarehouse: 'ҚОЙМАДА',
    yourStationDeparture: '+ сіздің станцияңыз = жөнелту',
    yourStationDestination: '+ сіздің станцияңыз = тағайындау орны',
    loaded: 'ТИЕЛДІ',
    inTransit: 'ЖОЛДА',
    arrived: 'ҚАБЫЛДАНДЫ',
    weighingCargo: 'Жүкті өлшеу',
    enterActualWeight: 'Нақты салмақты енгізіңіз (мәлімделген: {declared})',
    actualWeightPlaceholder: 'Нақты салмақ (мысалы: 15.5)',
    confirmWeight: 'Салмақты растау',
    scanQrPlaceholder: 'QR-кодты сканерлеңіз...',
    scanNumberPlaceholder: 'SH-XXXXXX енгізіңіз',
    processing: 'Өңделуде...',
    shipmentLoadedMsg: 'Жүк {num} тиелді ✓',
    shipmentIntakeMsg: 'Жүк {num} қоймаға қабылданды ✓',
    shipmentArrivedMsg: 'Жүк {num} қабылданды ✓',
    scanError: 'Сканерлеу қатесі',
    networkError: 'Желі қатесі. Қосылымды тексеріңіз.',
    extraChargeMsg: 'Қабылданды. Клиентке {charge} тг қосымша төлем туралы хабарлама жіберілді',
    weightConfirmError: 'Салмақты растау қатесі',
    success: 'СӘТТІ',
    alreadyProcessed: 'ӨҢДЕЛІП ҚОЙҒАН',
    error: 'ҚАТЕ',

    // Sidebar
    dashboard: 'Басқару панелі',
    pages: 'Беттер',
    newShipment: 'Жаңа жөнелту',

    transit: 'Транзит',
    arrival: 'Келу',
    reports: 'Есептер',
    wms: 'WMS қойма',
    settings: 'Баптаулар',
    userProfile: 'Пайдаланушы профилі',
    corporate: 'Корпоративті клиенттер',

    // New Shipment
    newShipmentTitle: 'Жаңа жөнелту',
    newShipmentDesc: 'Багажды тасымалдауды ресімдеу',
    clientInfo: 'Клиент туралы мәлімет',
    cargoDetails: 'Жүк туралы мәліметтер',
    payment: 'Төлем',

    // Client Info
    clientType: 'Клиент түрі',
    individual: 'Жеке тұлға',
    legal: 'Заңды тұлға',
    clientName: 'Аты-жөні / Ұйым атауы',
    enterClientName: 'Клиент атын енгізіңіз',
    clientSource: 'Клиент көзі',
    selectSource: 'Көзді таңдаңыз',
    directContact: 'Тікелей өтініш',
    contractNumber: 'Шарт нөмірі',
    depositSystem: 'Депозиттік жүйе',
    route: 'Бағыт',
    from: 'Қайдан',
    to: 'Қайда',
    selectStation: 'Станцияны таңдаңыз',
    departureDate: 'Жөнелту күні',
    transportCost: 'Тасымалдау құны',
    next: 'Әрі қарай',
    back: 'Артқа',
    receiverName: 'Алушының аты-жөні',
    enterReceiverName: 'Алушының атын енгізіңіз',
    receiverPhone: 'Алушының телефоны',
    recipientIsAnotherPerson: 'Алушы - басқа тұлға',
    doorToDoorDelivery: '«Есікке дейін» жеткізу',
    pickupAddress: 'Жүкті алу мекенжайы',
    deliveryAddress: 'Жеткізу мекенжайы',
    courierPhone: 'Байланыс телефоны (курьер үшін)',
    doorToDoorTitle: '«Есікке дейін» өтінімдер',
    doorToDoorDesc: 'Курьерлік жеткізу және шығу қызметін басқару',
    activeRequests: 'Белсенді өтінімдер',
    pickupLabel: 'Алу',
    deliveryLabel: 'Жеткізу',
    noDoorToDoor: '«Есікке дейін» өтінімдер жоқ',
    nothingFound: 'Ештеңе табылмады',
    loading: 'Жүктелуде...',
    optional: 'міндетті емес',
    searchByNumberOrClient: 'Нөмір немесе клиент бойынша іздеу...',

    // Cargo Details
    cargoDetailsTitle: 'Жүк туралы мәліметтер',
    mobiusTicket: 'Mobius билетін тексеру',
    hasTicket: 'Клиентте билет бар',
    ticketNumber: 'Билет нөмірі',
    ticketDiscount: 'Билет бойынша 50% жеңілдік қолданылды',
    weight: 'Салмақ (кг)',
    quantityPlaces: 'Орын саны',
    dimensionsPlaceholder: 'Ұзындығы × Ені × Биіктігі',
    cargoValue: 'Жүк құндылығы',
    fragile: 'Сынғыш',
    oversized: 'Габаритсіз',
    packaging: 'Қаптама',
    selectPackaging: 'Қаптама түрін таңдаңыз',
    woodCrate: 'Ағаш қаптама',
    stretchFilm: 'Стретч-пленка',
    cardboard: 'Картон қорап',
    bag: 'Қап',
    noPackaging: 'Қаптамасыз',
    declaredValue: 'Жариялаған құны (₸)',
    cargoDescription: 'Жүктің сипаттамасы',
    describeContent: 'Багаж мазмұнын сипаттаңыз',

    // Payment
    tariffCalculation: 'Тариф есебі',
    baseTransportCost: 'Тасымалдаудың базалық құны:',
    weightSurcharge: 'Салмақ үшін қосымша төлем:',
    fragileCargo: 'Сынғыш жүк:',
    oversizedCargo: 'Габаритсіз жүк:',
    ticketDiscountLabel: 'Билет бойынша жеңілдік (50%):',
    totalPayment: 'Барлығы төлеу керек:',
    emailReceipt: 'Чек үшін Email',
    cardInfo: 'Карта туралы мәлімет',
    cardholderName: 'Карта иесінің аты',
    countryRegion: 'Ел немесе аймақ',
    postalCode: 'Индекс',
    payButton: 'Төлеу',
    termsAgree: '"Төлеу" түймесін басу арқылы сіз келісесіз',
    termsOfUse: 'Пайдалану шарттарымен',
    privacyPolicy: 'Құпиялылық саясатымен',
    and: 'және',

    // Active Shipments
    activeShipmentsTitle: 'Белсенді жөнелтулер',
    activeShipmentsDesc: 'Өңдеудегі жөнелтулер тізімі',
    searchPlaceholder: 'Жөнелту нөмірі, клиент бойынша іздеу...',
    filters: 'Сүзгілер',
    number: 'Нөмір',
    client: 'Клиент',
    routeColumn: 'Бағыт',
    weightColumn: 'Салмақ',
    date: 'Күн',
    status: 'Күй',
    actions: 'Әрекеттер',
    details: 'Толығырақ',
    inTransit: 'Жолда',
    loaded: 'Тиелген',
    arrived: 'Келді',
    statusPaid: 'Төленді',
    paymentPending: 'Төлем күтілуде',

    // Shipment Details
    mainInfo: 'Негізгі ақпарат',
    routeInfo: 'Маршрут',
    receiverOther: 'Алушы (басқа тұлға)',
    cargoParams: 'Жүк параметрлері',
    downloadWaybill: 'Жүкқұжатты жүктеу',
    downloadSurrenderList: 'Тапсыру тізімін жүктеу',
    statusPickup: 'Алып кету',
    statusDelivery: 'Жеткізу',
    statusWaiting: 'Күтуде',
    statusInWork: 'Жұмыста',
    statusDoorToDoor: 'Үйден үйге',

    // Transit
    transitTitle: 'Транзит',
    transitDesc: 'Багаж қозғалысын тіркеу',
    qrScanning: 'QR-кодты ска��ерлеу',
    scanQrDesc: 'Тіркеу үшін багаждағы QR-кодты сканерлеңіз',
    startScanning: 'Сканерлеуді бастау',
    recentScans: 'Соңғы сканерлеулер',
    transitLoading: 'Тиеу',
    arrivalScan: 'Келу',
    issuance: 'Беру',
    action: 'Әрекет',

    // Arrival
    arrivalTitle: 'Келу',
    arrivalDesc: 'Келген багажды басқару',
    arrivedShipments: 'Келген жөнелтулер',
    notifyAll: 'Барлығын хабарландыру',
    notified: 'Хабарландырылды',
    arrivedFrom: 'Қайдан:',
    arrivedAt: 'Келді:',
    phone: 'Телефон:',
    notify: 'Хабарландыру',
    issue: 'Беру',
    scanForIssue: 'Беру үшін жүкті сканерлеу',
    barcodePlaceholder: 'Штрих-кодты сканермен оқыңыз...',
    noArrivals: 'Берілуін күтіп тұрған жүктер жоқ',
    issueBaggage: 'Жүкті беру',
    recipientName: 'Алушының аты',
    fullNameByDoc: 'Құжат бойынша аты-жөні',
    recipientPhone: 'Алушының телефоны',
    phonePlaceholder: '+7 (___) ___-__-__',
    errorProvideNamePhone: 'Аты-жөнін және телефонын көрсетіңіз',
    errorSurchargeNeeded: 'Алдымен қосымша төлем алу қажет',
    errorReceiverMismatch: 'Алушы мәліметтері сәйкес келмейді. Дұрыс аты-жөні мен телефонын көрсетіңіз.',
    scanSuccess: 'Жүк сәтті сканерленді',
    scanError: 'Сканерлеу қатесі',

    // Reports
    reportsTitle: 'Есептер',
    reportsDesc: 'Есептерді қалыптастыру және қарау',
    fo3Report: 'FO-3 есебі',
    financialReport: 'Қаржылық есеп',
    shipmentsReport: 'Жөнелтулер бойынша есеп',
    generalStats: 'Жалпы статистика',
    auditLog: 'Аудит журналы',
    userActions: 'Пайдаланушы әрекеттері',
    routeReport: 'Бағыттар бойынша есеп',
    routeAnalysis: 'Бағыттарды талдау',
    allUsers: 'Барлық пайдаланушылар',
    allRoutes: 'Барлық бағыттар',
    generate: 'Қалыптастыру',
    export: 'Жүктеп алу',

    // WMS
    wmsTitle: 'WMS қойма',
    wmsDesc: 'Автоматтандырылған қойма ұяшықтары жүйесі',
    storageCells: 'Қойма ұяшықтары',
    cellStatus: 'Ұяшықтар күйі',
    free: 'Бос',
    occupied: 'Толық',
    maintenance: 'Қызмет көрсету',
    selfService: 'Өзін-өзі қызмет көрсету',
    selfServiceDesc: 'Менеджерсіз багаж тапсыру',
    scanDocument: 'Құжатты сканерлеу',
    scanDocumentDesc: 'Бастау үшін төлқұжатты немесе QR-кодты сканерлеңіз',
    placeInCell: 'Ұяшыққа салыңыз',
    placeInCellDesc: 'Ұяшықты ашып, багажды ішіне салыңыз',
    autoMeasure: 'Автоматты өлшеу',
    autoMeasureDesc: 'Салмақ пен өлшемдер автоматты түрде өлшенеді',
    confirmShipment: 'Жөнелтуді растаңыз',
    confirmShipmentDesc: 'Деректерді тексеріп, QR-кодты алыңыз',
    cellNumber: 'Ұяшық',
    openCell: 'Ұяшықты ашу',
    closeCell: 'Ұяшықты жабу',

    // Settings
    settingsTitle: 'Баптаулар',
    settingsDesc: 'Жүйе және профиль баптаулары',
    languageSettings: 'Интерфейс тілі',
    themeSettings: 'Тақырып',
    light: 'Ашық',
    dark: 'Қараңғы',
    notificationSettings: 'Хабарландырулар',
    emailNotifications: 'Email хабарландырулары',
    smsNotifications: 'SMS хабарландырулары',
    saveSettings: 'Баптауларды сақтау',

    // Common
    cancel: 'Болдырмау',
    confirm: 'Растау',
    close: 'Жабу',
    save: 'Сақтау',
    delete: 'Жою',
    edit: 'Өңдеу',

    // Shipment created
    shipmentCreated: 'Жөнелту жасалды',
    documentsReady: 'Құжаттар қалыптастырылды және басып шығаруға дайын',
    printDocuments: 'Құжаттарды басып шығару',
    newShipmentButton: 'Жаңа жөнелту',

    // Manager Dashboard
    managerDashboard: 'Менеджер панелі',
    managerDashboardDesc: 'Аналитика және жүйенің іштету статистикасы',
    monthlyShipments: 'Айлық жөнелтулер',
    completedShipments: 'Жүргізілген жөнелтулер',
    activeContracts: 'Активті шарттар',
    wagonsInWork: 'Жұмысдағы вагондар',
    month: 'Ай',
    active: 'Активті',
    total: 'Жалпы',
    vsLastMonth: 'өтінген айға қарау',
    planCompletion: 'планды орындалдыру',
    newPerWeek: 'жетідеңде жаңа',
    withCargo: 'жүктің астында',
    routeAnalysisTitle: 'Бағыттарды талдау',
    topRoutes: 'Жоғары бағыттар',
    shipments: 'жөнелтулер',
    wagonStatusTitle: 'Вагондардың күйі',
    underCargo: 'Жүктің астында',
    atStation: 'Станцияда',
    inIdle: 'Тұрғыз',
    empty: 'Бос',
    inRepair: 'Түзету үшін',
    financialMetrics: 'Финансалық мәліметтер',
    revenue: 'Келісім',
    expenses: 'Шығу',
    profit: 'Жылдамдық',
    currentMonth: 'Ағымдағы ай',
    thisMonthLabel: 'Бұл ай',
    thisQuarter: 'Бұл қыртышақ',
    revenueByRoute: 'Бағыттар бойынша келісім',
    totalRevenue: 'Жалпы келісім',
    wagonsByStatus: 'Вагондардың күйі бойынша',
    wagons: 'вагондар',

    plannedActual: 'Пландағы және фактическі мәліметтер',
    positiveTrend: 'Позитивті тенденция',
    halfYearPlan: 'Жарым жылдық план',
    actualRevenue: 'Фактическі келісім',
    planExecution: 'Планды орындалдыру',
    planned: 'Пландағы',
    actual: 'Фактическі',

    // Admin Dashboard
    adminDashboard: 'Басқару панелі',
    employeeManagement: 'Қызметкерлерді басқару',
    employeeManagementDesc: 'Қызметкерлерді тіркеу және басқару',
    totalEmployees: 'Барлық қызметкерлер',
    activeEmployees: 'Активті',
    operators: 'Менеджерлер',
    receivers: 'Қабылдаушылар',
    createEmployee: 'Қызметкер тіркемесін жасау',
    name: 'Аты',
    email: 'Email',
    role: 'Рөл',
    station: 'Станция',
    createdAt: 'Тіркелген күні',
    statusEmployee: 'Күйі',
    actionsEmployee: 'Әрекеттер',
    createNewEmployee: 'Жаңа қызметкер тіркемесін жасау',
    fullName: 'Толық аты',
    enterFullName: 'Толық атын енгізіңіз',
    enterEmail: 'Email-ді енгізіңіз',
    password: 'Құпия сөз',
    enterPassword: 'Құпия сөзді енгізіңіз',
    operator: 'Менеджер',
    receiver: 'Қабылдаушы',
    roleAdmin: 'Әкімші',
    roleManager: 'Менеджер',
    roleAuditor: 'Ревизор',
    roleMobileGroup: 'Мобильді топ',
    roleTrainReceiver: 'Пойыздағы қабылдаушы',
    roleDirectionHead: 'Бағыт басшысы',
    roleChiefHead: 'Басшы',
    roleCourier: 'Курьер',



    // ActiveShipmentDetails
    created: 'Жасалды',
    printLabels: 'Жапсырмаларды басып шығару',
    doorToDoorAddresses: '«Есікке дейін» мекенжайлары',
    qrForScanner: 'Сканер үшін QR-код',
    pcs: 'дана',
    contactPhone: 'Байланыс телефоны',
    readyStatus: 'Дайындыққа қарай',

    // Courier Dashboard
    tasksTitle: 'Тапсырмалар',
    availableTasks: 'Қолжетімді тапсырмалар',
    myTasks: 'Менің тапсырмаларым',
    noTasks: 'Тапсырмалар жоқ',
    pickupType: 'Алу',
    deliveryType: 'Жеткізу',
    addressNotSpecified: 'Мекенжай көрсетілмеген',
    activeBadge: 'Белсенді',
    noStation: 'Станция жоқ',
    takeTask: 'Тапсырманы алу',
    deliveredToReceiver: 'Алушыға жеткізілді',
    pickedUpFromClient: 'Клиенттен алынды',
    handOverToStation: 'Станцияға тапсырыңыз',
    callClient: 'Қоңырау шалу',
    open2Gis: '2GIS ашу',
    courierStatusWaitingPickup: 'Алуды күтуде',
    courierStatusAssigned: 'Клиентке бара жатырсыз',
    courierStatusPickedUp: 'Сізде (станцияға тапсыру керек)',
    courierStatusWaitingDelivery: 'Жеткізуді күтуде',
    courierStatusDelivered: 'Жеткізілді',
    courierStatusLoaded: 'Станцияға тапсырылды',

    // Shipment statuses (IndividualDashboard)
    statusRegistered: 'Тіркелген',
    statusLoaded: 'Жүктелген',
    statusInTransit: 'Жолда',
    statusArrived: 'Жетті',
    statusReadyForIssue: 'Беруге дайын',
    statusIssued: 'Берілген',
    clickForDetails: 'Толығырақ басыңыз',
    myShipments: 'Менің жөнелтулерім',
    createButton: 'Жасау',
    searchByNameEmail: 'Аты, email немесе станция бойынша іздеу...',
    newEmployee: 'Жаңа қызметкер',
    employeeCreatedSuccess: 'Қызметкер сәтті тіркелген!',
    deleteEmployeeConfirm: 'Бұл қызметкерді өшіру керек пішіндеңіз бе?',
    employeeLabel: 'Қызметкер',
    dateCreated: 'Тіркелген күні',
    activeStatus: 'Активті',
    inactiveStatus: 'Пассивті',
    noEmployeesFound: 'Қызметкерлер табылған жок',

    // Corporate Dashboard
    corporateDashboard: 'Корпоративті панель',
    corporateClientsDesc: 'Заңды тұлғаларды басқару',
    addClient: 'Клиент қосу',
    searchByNameOrContract: 'Аты немесе шарт бойынша іздеу...',
    noCorporateClients: 'Корпоративті клиенттер жоқ.',
    withoutName: 'Атаусыз',
    activeCount: 'белсенді',
    binContract: 'БСН/Шарт:',
    contactPerson: 'Байланыс тұлғасы:',
    depositSumMsg: 'Толықтыру сомасы (₸):',
    addCorporateClient: 'Корпоративті клиент қосу',
    companyName: 'Компания атауы',
    bin: 'БСН',
    // fullName: 'Аты-жөні',
    passwordLabel: 'Құпия сөз',
    depositAmount: 'Депозитті толтыру сомасы (₸)',
    // cancel: 'Болдырмау',
    createClient: 'Клиентті құру',
    creating: 'Құрылуда...',
    topUpDeposit: 'Депозитті толтыру',
    topUpAmount: 'Толықтыру сомасы (₸)',
    paymentMethod: 'Төлем әдісі',
    bankCard: 'Банк картасы (Kaspi, Halyk)',
    pay: 'Төлеу',
    processing: 'Өңделуде...',
    topUp: 'Толықтыру',
    myShipmentsDesc: 'Корпоративтік тасымалдарды басқару',
    activeShipments: 'Белсенді жөнелтулер',
    pendingPickup: 'Алып кетуді күтуде',
    totalThisMonth: 'Бір айдағы барлығы',
    avgDeliveryTime: 'Орташа жеткізу уақыты',
    days: 'күн',
    createNewShipment: 'Жөнелтуді жасау',
    recentShipments: 'Жақындағы жөнелтулер',
    viewAll: 'Барлығын көру',
    deposit: 'Депозит',
    thisMonth: 'Бір айда',
    documents: 'Құжаттар',
    generateDocuments: 'Құжаттарды қалыптастыру',
    invoice: 'Шот-фактура',
    actOfWork: 'Орындалған жұмыстар актісі',

    waybillRegistry: 'Жүкқұжаттар тізілімі',

    // Individual Dashboard
    individualDashboard: 'Жеке кабинет',
    myBaggage: 'Менің багаждым',
    myBaggageDesc: 'Жөнелтулерді көзделу',
    trackShipment: 'Жөнелтуді көзделу',
    trackingNumber: 'Жөнелту нөмірі',
    enterTrackingNumber: 'Жөнелту нөмірін енгізіңіз',
    track: 'Көзделу',
    noShipmentsYet: 'Жөнелтулеріңіз жетіп келген жок',
    createFirstShipment: 'Бірінші жөнелтуді жасаңыз',

    // Receiver Dashboard
    receiverDashboard: 'Қабылдаушы панелі',
    baggageIssuance: 'Багажды беру',
    baggageIssuanceDesc: 'Багажды беруді басқару',
    readyForPickup: 'Қабылдауға дайын',
    issuedToday: 'Бүгін берілген',
    notifiedClients: 'Клиенттерге хабарландырылды',
    avgWaitTime: 'Орта күту уақыты',
    minutes: 'минут',
    scanOrEnter: 'Сканерлеу немесе енгізу',
    scanQrOrEnter: 'QR-кодты сканерлеу немесе жөнелту нөмірін енгізу',
    shipmentNumber: 'Жөнелту нөмірі',
    enterShipmentNumber: 'Жөнелту нөмірін енгізіңіз',
    findShipment: 'Жөнелтуді табу',
    readyForIssue: 'Беру үшін дайын',
    issueToClient: 'Клиентке беру',

    paymentLog: 'Төлемдер журналы',
    paymentLogDesc: 'Төлем тарихы',
    totalSum: 'Жалпы сома',
    confirmDeleteClient: 'Бұл клиентті жойғыңыз келетініне сенімдісіз бе?',

    // Receiver Tabs
    loadingPlan: 'Жоспар',
    arrivalTab: 'Келу',
    auditTab: 'Журнал',
    searchLogs: 'Жүк ID, әрекет бойынша іздеу...',
    noLogs: 'Журналда жазбалар жоқ.',
    entity: 'Нысан',
    newValue: 'Жаңа мән: ',
    noCargoToLoad: 'Жүктеуге жүк жоқ',
    scanQrPlaceholder: 'QR-код сканерлеңіз...',
    loadButton: 'Жүктеу',

    // Mobile Group (AuditorTerminal)
    logoutBtn: 'Шығу',
    networkError: 'Желі қатесі',
    mobileGroupReady: 'Сканерлеуге дайын',
    mobileGroupTitle: 'Мобильді топ',
    mobileGroupSubtitle: 'Станция',
    mobileGroupStationNotSet: 'Станция белгіленбеген',
    mobileGroupChecked: 'Тексерілді',
    mobileGroupApproved: 'Мақұлданды',
    mobileGroupRejected: 'Қабылданбады',
    mobileGroupMismatch: 'Станция сәйкессіздігі',
    mobileGroupShift: 'Ауысым',
    mobileGroupScanTitle: 'Жүкті сканерлеу',
    mobileGroupScanDesc: 'Жөнелту нөмірін қолмен енгізіңіз немесе сканерді пайдаланыңыз — тексеру үшін Enter басыңыз',
    mobileGroupScanPlaceholder: 'Сканерді бағыттаңыз немесе нөмірді енгізіңіз...',
    mobileGroupChecking: 'Тексерілуде...',
    mobileGroupCheckButton: 'Жүкті тексеру',
    mobileGroupReadOnly: 'Тек оқу режимі — жүктің мәртебесі өзгермейді',
    mobileGroupHistory: 'Тексеру журналы',
    mobileGroupSuccess: 'СӘТТІ',
    mobileGroupError: 'ҚАТЕ',
    mobileGroupRoute: 'Бағыт:',
    mobileGroupCurrentStation: 'Ағымдағы станция:',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('lang');
    if (saved === 'ru' || saved === 'en' || saved === 'kk') return saved;
    return 'ru';
  });

  const handleSetLanguage = (lang: Language) => {
    localStorage.setItem('lang', lang);
    setLanguage(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ru] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}