import { QRCodeSVG } from 'qrcode.react';
import { Package, Truck, Calendar, MapPin, User, Phone } from 'lucide-react';

interface ShipmentLabelProps {
    data: any; // Ideally this should be a proper type
    t: (key: string) => string;
}

export function ShipmentLabel({ data, t }: ShipmentLabelProps) {
    // Using a specific class that will be targeted by media print query
    return (
        <div className="hidden print:block print:w-full print:h-screen bg-white p-8">
            <div className="border-4 border-black p-6 max-w-[100mm] mx-auto">
                {/* Header */}
                <div className="text-center border-b-2 border-black pb-4 mb-4">
                    <h1 className="text-2xl font-bold uppercase">CargoTrans</h1>
                    <p className="text-sm">Station Almaty-1</p>
                </div>

                {/* Route */}
                <div className="mb-6">
                    <div className="flex justify-between items-center mb-2">
                        <span className="text-3xl font-bold">{data.fromStation.substring(0, 3).toUpperCase()}</span>
                        <Truck className="w-8 h-8" />
                        <span className="text-3xl font-bold">{data.toStation.substring(0, 3).toUpperCase()}</span>
                    </div>
                    <div className="text-center text-sm font-bold border rounded px-2 py-1 bg-gray-100 print:bg-gray-100">
                        {data.fromStation} — {data.toStation}
                    </div>
                </div>

                {/* Date & Cargo */}
                <div className="grid grid-cols-2 gap-4 mb-6 border-b-2 border-black pb-6">
                    <div>
                        <p className="text-xs text-gray-500 uppercase">Data</p>
                        <p className="font-bold">{new Date(data.departureDate).toLocaleDateString()}</p>
                    </div>
                    <div>
                        <p className="text-xs text-gray-500 uppercase">Weight</p>
                        <p className="font-bold">{data.weight} kg</p>
                    </div>
                    <div>
                        <p className="text-xs text-gray-500 uppercase">Dims</p>
                        <p className="font-bold">{data.dimensions}</p>
                    </div>
                    <div>
                        <p className="text-xs text-gray-500 uppercase">Pack</p>
                        <p className="font-bold">{data.packaging}</p>
                    </div>
                </div>

                {/* Client & Receiver */}
                <div className="mb-6 space-y-4">
                    <div>
                        <p className="text-xs text-gray-500 uppercase mb-1">Sender</p>
                        <p className="font-bold text-sm truncate">{data.clientName}</p>
                        <p className="text-sm">{data.clientPhone}</p>
                    </div>

                    <div className="border-t border-dashed border-gray-400 pt-2">
                        <p className="text-xs text-gray-500 uppercase mb-1">Receiver</p>
                        <p className="font-bold text-sm truncate">
                            {data.receiverName || data.clientName}
                        </p>
                        <p className="text-sm">
                            {data.receiverPhone || data.clientPhone}
                        </p>
                    </div>
                </div>

                {/* QR Code */}
                <div className="flex flex-col items-center justify-center pt-2">
                    <QRCodeSVG
                        value={JSON.stringify({
                            id: data.id || ('SH-' + Math.floor(Math.random() * 10000)), // Use actual ID if available
                            from: data.fromStation,
                            to: data.toStation,
                            client: data.clientName
                        })}
                        size={128}
                    />
                    <p className="mt-2 text-xs font-mono">Scan for tracking</p>
                </div>

                {/* Footer */}
                <div className="mt-6 text-center text-xs text-gray-400">
                    Generated by CargoTrans System
                </div>
            </div>
        </div>
    );
}
